-- 082 — KATALOG STARTOWY BIBLIOTEKI ŹRÓDEŁ RSS (419 wpisów).
--
-- Osobna migracja od DDL (0254) świadomie: przegląd zmiany schematu nie ma tonąć w kilkuset
-- wierszach danych, a te dane nie mają wracać do przeglądu przy każdej zmianie tabeli.
--
-- IDEMPOTENTNOŚĆ (C-14): `ON CONFLICT ("key") DO NOTHING` — nigdy `DO UPDATE`. Ponowne
-- uruchomienie migracji (albo dopisanie kolejnego wsadu w przyszłości) NIE MOŻE nadpisać
-- poprawki administratora: adres kanału bywa poprawiany właśnie dlatego, że wersja z seedu
-- przestała działać, więc przywrócenie jej byłoby cofnięciem naprawy.
--
-- Wpisy dobrane ręcznie. Przy tej skali martwy kanał jest kwestią czasu, nie ryzykiem — dlatego
-- tabela ma `checkStatus`/`checkedAt`/`checkNote`, a panel administratora akcję „Sprawdź" oraz
-- wyłączenie wpisu jednym ruchem (`/admin/zrodla-rss`).
--
-- Wycofanie: DELETE FROM "NewsSourceCatalog"; (tabela nie trzyma danych użytkownika — dodanie
-- źródła KOPIUJE wpis do `NewsSource`, więc skasowanie katalogu nikomu nic nie zabiera).

-- Wsad 1/9 — kraje: PL
INSERT INTO "NewsSourceCatalog" ("id","key","name","rssUrl","homepageUrl","descriptor","country","language","category","sortOrder","createdAt","updatedAt") VALUES
  (gen_random_uuid()::text, 'onet-wiadomosci', 'Onet Wiadomości', 'https://wiadomosci.onet.pl/.feed', 'https://wiadomosci.onet.pl', 'Portal, centrum', 'PL', 'pl', 'wiadomosci', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'wp-wiadomosci', 'Wirtualna Polska — Wiadomości', 'https://wiadomosci.wp.pl/rss.xml', 'https://wiadomosci.wp.pl', 'Portal', 'PL', 'pl', 'wiadomosci', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'interia-fakty', 'Interia Fakty', 'https://fakty.interia.pl/feed', 'https://fakty.interia.pl', 'Portal', 'PL', 'pl', 'wiadomosci', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'gazeta-wiadomosci', 'Gazeta.pl Wiadomości', 'https://wiadomosci.gazeta.pl/pub/rss/wiadomosci.htm', 'https://wiadomosci.gazeta.pl', 'Portal, lewa strona', 'PL', 'pl', 'wiadomosci', 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'tvn24', 'TVN24', 'https://tvn24.pl/najwazniejsze.xml', 'https://tvn24.pl', 'Telewizja informacyjna', 'PL', 'pl', 'wiadomosci', 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'polsat-news', 'Polsat News', 'https://www.polsatnews.pl/rss/wszystkie.xml', 'https://www.polsatnews.pl', 'Telewizja informacyjna', 'PL', 'pl', 'wiadomosci', 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'rmf24', 'RMF24', 'https://www.rmf24.pl/fakty/feed', 'https://www.rmf24.pl', 'Radio informacyjne', 'PL', 'pl', 'wiadomosci', 7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'radio-zet', 'Radio ZET Wiadomości', 'https://wiadomosci.radiozet.pl/rss.xml', 'https://wiadomosci.radiozet.pl', 'Radio', 'PL', 'pl', 'wiadomosci', 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'tok-fm', 'TOK FM', 'https://www.tokfm.pl/pub/rss/tokfm_najnowsze.htm', 'https://www.tokfm.pl', 'Radio, lewa strona', 'PL', 'pl', 'wiadomosci', 9, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'polskie-radio-24', 'Polskie Radio 24', 'https://polskieradio24.pl/rss/wszystkie.xml', 'https://polskieradio24.pl', 'Radio publiczne', 'PL', 'pl', 'wiadomosci', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'pap', 'Polska Agencja Prasowa', 'https://www.pap.pl/rss.xml', 'https://www.pap.pl', 'Agencja prasowa', 'PL', 'pl', 'wiadomosci', 11, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'tvp-info', 'TVP Info', 'https://www.tvp.info/rss.xml', 'https://www.tvp.info', 'Telewizja publiczna', 'PL', 'pl', 'wiadomosci', 12, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'rp-pl', 'Rzeczpospolita', 'https://www.rp.pl/rss/1019', 'https://www.rp.pl', 'Dziennik, prawa strona centrum', 'PL', 'pl', 'wiadomosci', 13, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'dziennik-pl', 'Dziennik.pl', 'https://wiadomosci.dziennik.pl/rss.xml', 'https://wiadomosci.dziennik.pl', 'Dziennik', 'PL', 'pl', 'wiadomosci', 14, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'newsweek-pl', 'Newsweek Polska', 'https://www.newsweek.pl/rss.xml', 'https://www.newsweek.pl', 'Tygodnik, lewa strona', 'PL', 'pl', 'wiadomosci', 15, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'polityka', 'Polityka', 'https://www.polityka.pl/rss/kraj.xml', 'https://www.polityka.pl', 'Tygodnik, lewa strona', 'PL', 'pl', 'opinie', 16, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'do-rzeczy', 'Do Rzeczy', 'https://dorzeczy.pl/rss', 'https://dorzeczy.pl', 'Tygodnik, prawa strona', 'PL', 'pl', 'opinie', 17, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'wprost', 'Wprost', 'https://www.wprost.pl/rss.xml', 'https://www.wprost.pl', 'Tygodnik', 'PL', 'pl', 'wiadomosci', 18, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'sieci-prawdy', 'wPolityce', 'https://wpolityce.pl/rss/wszystko.xml', 'https://wpolityce.pl', 'Prawa strona', 'PL', 'pl', 'opinie', 19, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'niezalezna', 'Niezależna', 'https://niezalezna.pl/rss', 'https://niezalezna.pl', 'Prawa strona', 'PL', 'pl', 'wiadomosci', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'oko-press', 'OKO.press', 'https://oko.press/feed', 'https://oko.press', 'Dziennikarstwo śledcze, lewa strona', 'PL', 'pl', 'opinie', 21, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'krytyka-polityczna', 'Krytyka Polityczna', 'https://krytykapolityczna.pl/feed/', 'https://krytykapolityczna.pl', 'Lewa strona', 'PL', 'pl', 'opinie', 22, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'nowa-konfederacja', 'Nowa Konfederacja', 'https://nowakonfederacja.pl/feed/', 'https://nowakonfederacja.pl', 'Konserwatywno-liberalny', 'PL', 'pl', 'opinie', 23, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'klub-jagiellonski', 'Klub Jagielloński', 'https://klubjagiellonski.pl/feed/', 'https://klubjagiellonski.pl', 'Think tank', 'PL', 'pl', 'opinie', 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'wiez', 'Więź', 'https://wiez.pl/feed/', 'https://wiez.pl', 'Katolicki, otwarty', 'PL', 'pl', 'opinie', 25, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'gosc-niedzielny', 'Gość Niedzielny', 'https://www.gosc.pl/rss/1.xml', 'https://www.gosc.pl', 'Katolicki', 'PL', 'pl', 'wiadomosci', 26, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'deon', 'Deon.pl', 'https://deon.pl/rss', 'https://deon.pl', 'Katolicki', 'PL', 'pl', 'wiadomosci', 27, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'kai', 'Katolicka Agencja Informacyjna', 'https://www.ekai.pl/feed/', 'https://www.ekai.pl', 'Agencja katolicka', 'PL', 'pl', 'wiadomosci', 28, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'salon24', 'Salon24', 'https://www.salon24.pl/feed/', 'https://www.salon24.pl', 'Blogi publicystyczne', 'PL', 'pl', 'opinie', 29, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, '300polityka', '300Gospodarka', 'https://300gospodarka.pl/feed', 'https://300gospodarka.pl', 'Gospodarka', 'PL', 'pl', 'biznes', 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'konkret24', 'Konkret24', 'https://konkret24.tvn24.pl/rss.xml', 'https://konkret24.tvn24.pl', 'Weryfikacja faktów', 'PL', 'pl', 'wiadomosci', 31, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'demagog', 'Demagog', 'https://demagog.org.pl/feed/', 'https://demagog.org.pl', 'Weryfikacja faktów', 'PL', 'pl', 'wiadomosci', 32, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'notes-from-poland', 'Notes from Poland', 'https://notesfrompoland.com/feed/', 'https://notesfrompoland.com', 'Polska po angielsku', 'PL', 'pl', 'wiadomosci', 33, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'tvn24-biznes', 'TVN24 Biznes', 'https://tvn24.pl/biznes.xml', 'https://tvn24.pl/biznes', 'Telewizja, gospodarka', 'PL', 'pl', 'biznes', 34, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'money-pl', 'Money.pl', 'https://www.money.pl/rss/all', 'https://www.money.pl', 'Finanse', 'PL', 'pl', 'biznes', 35, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'bankier', 'Bankier.pl', 'https://www.bankier.pl/rss/wiadomosci.xml', 'https://www.bankier.pl', 'Finanse i giełda', 'PL', 'pl', 'biznes', 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'puls-biznesu', 'Puls Biznesu', 'https://www.pb.pl/rss', 'https://www.pb.pl', 'Dziennik gospodarczy', 'PL', 'pl', 'biznes', 37, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'business-insider-pl', 'Business Insider Polska', 'https://businessinsider.com.pl/.feed', 'https://businessinsider.com.pl', 'Biznes', 'PL', 'pl', 'biznes', 38, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'forbes-pl', 'Forbes Polska', 'https://www.forbes.pl/rss.xml', 'https://www.forbes.pl', 'Biznes', 'PL', 'pl', 'biznes', 39, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'parkiet', 'Parkiet', 'https://www.parkiet.com/rss/1017', 'https://www.parkiet.com', 'Giełda', 'PL', 'pl', 'biznes', 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'stockwatch', 'StockWatch.pl', 'https://www.stockwatch.pl/feed/', 'https://www.stockwatch.pl', 'Giełda', 'PL', 'pl', 'biznes', 41, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'obserwator-finansowy', 'Obserwator Finansowy', 'https://www.obserwatorfinansowy.pl/feed/', 'https://www.obserwatorfinansowy.pl', 'NBP, analizy', 'PL', 'pl', 'biznes', 42, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'wnp', 'WNP.pl', 'https://www.wnp.pl/rss/serwis_rss.xml', 'https://www.wnp.pl', 'Przemysł', 'PL', 'pl', 'biznes', 43, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'cire', 'CIRE — energetyka', 'https://www.cire.pl/rss', 'https://www.cire.pl', 'Energetyka', 'PL', 'pl', 'biznes', 44, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'wysokie-napiecie', 'WysokieNapiecie.pl', 'https://wysokienapiecie.pl/feed/', 'https://wysokienapiecie.pl', 'Energetyka', 'PL', 'pl', 'biznes', 45, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'prawo-pl', 'Prawo.pl', 'https://www.prawo.pl/rss', 'https://www.prawo.pl', 'Prawo', 'PL', 'pl', 'biznes', 46, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'mycompanypolska', 'My Company Polska', 'https://mycompanypolska.pl/rss', 'https://mycompanypolska.pl', 'Przedsiębiorczość', 'PL', 'pl', 'biznes', 47, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'gazeta-prawna', 'Gazeta Prawna', 'https://www.gazetaprawna.pl/rss.xml', 'https://www.gazetaprawna.pl', 'Prawo i podatki', 'PL', 'pl', 'biznes', 48, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'xyz-nieruchomosci', 'Rynek Pierwotny', 'https://rynekpierwotny.pl/feed/', 'https://rynekpierwotny.pl', 'Nieruchomości', 'PL', 'pl', 'biznes', 49, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'comparic', 'Comparic', 'https://comparic.pl/feed/', 'https://comparic.pl', 'Rynki finansowe', 'PL', 'pl', 'biznes', 50, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("key") DO NOTHING;

-- Wsad 2/9 — kraje: PL
INSERT INTO "NewsSourceCatalog" ("id","key","name","rssUrl","homepageUrl","descriptor","country","language","category","sortOrder","createdAt","updatedAt") VALUES
  (gen_random_uuid()::text, 'spidersweb', 'Spider''s Web', 'https://spidersweb.pl/feed', 'https://spidersweb.pl', 'Technologia', 'PL', 'pl', 'technologia', 51, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'antyweb', 'Antyweb', 'https://antyweb.pl/feed', 'https://antyweb.pl', 'Technologia', 'PL', 'pl', 'technologia', 52, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'dobreprogramy', 'dobreprogramy', 'https://www.dobreprogramy.pl/feed', 'https://www.dobreprogramy.pl', 'Technologia', 'PL', 'pl', 'technologia', 53, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'benchmark', 'Benchmark.pl', 'https://www.benchmark.pl/rss/aktualnosci-full.xml', 'https://www.benchmark.pl', 'Sprzęt', 'PL', 'pl', 'technologia', 54, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'purepc', 'PurePC', 'https://www.purepc.pl/rss.xml', 'https://www.purepc.pl', 'Sprzęt', 'PL', 'pl', 'technologia', 55, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'ithardware', 'ITHardware', 'https://ithardware.pl/rss', 'https://ithardware.pl', 'Sprzęt', 'PL', 'pl', 'technologia', 56, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'komputer-swiat', 'Komputer Świat', 'https://www.komputerswiat.pl/.feed', 'https://www.komputerswiat.pl', 'Technologia', 'PL', 'pl', 'technologia', 57, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'chip-pl', 'CHIP', 'https://www.chip.pl/feed', 'https://www.chip.pl', 'Technologia', 'PL', 'pl', 'technologia', 58, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'tabletowo', 'Tabletowo', 'https://www.tabletowo.pl/feed/', 'https://www.tabletowo.pl', 'Mobilne', 'PL', 'pl', 'technologia', 59, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'android-com-pl', 'Android.com.pl', 'https://android.com.pl/feed/', 'https://android.com.pl', 'Mobilne', 'PL', 'pl', 'technologia', 60, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'telepolis', 'Telepolis', 'https://www.telepolis.pl/rss', 'https://www.telepolis.pl', 'Telekomunikacja', 'PL', 'pl', 'technologia', 61, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'gsmmaniak', 'GSMManiaK', 'https://gsmmaniak.pl/feed/', 'https://gsmmaniak.pl', 'Mobilne', 'PL', 'pl', 'technologia', 62, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'niebezpiecznik', 'Niebezpiecznik', 'https://niebezpiecznik.pl/feed/', 'https://niebezpiecznik.pl', 'Bezpieczeństwo', 'PL', 'pl', 'technologia', 63, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'zaufana-trzecia-strona', 'Zaufana Trzecia Strona', 'https://zaufanatrzeciastrona.pl/feed/', 'https://zaufanatrzeciastrona.pl', 'Bezpieczeństwo', 'PL', 'pl', 'technologia', 64, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'sekurak', 'Sekurak', 'https://sekurak.pl/feed/', 'https://sekurak.pl', 'Bezpieczeństwo', 'PL', 'pl', 'technologia', 65, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'cyberdefence24', 'CyberDefence24', 'https://cyberdefence24.pl/_RSS', 'https://cyberdefence24.pl', 'Cyberbezpieczeństwo', 'PL', 'pl', 'technologia', 66, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'bulldogjob', 'Bulldogjob', 'https://bulldogjob.pl/rss', 'https://bulldogjob.pl', 'Programowanie', 'PL', 'pl', 'technologia', 67, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'just-geek-it', 'JustJoin.it Blog', 'https://geek.justjoin.it/feed', 'https://geek.justjoin.it', 'Programowanie', 'PL', 'pl', 'technologia', 68, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'mambiznes', 'MamBiznes', 'https://mambiznes.pl/feed', 'https://mambiznes.pl', 'Startupy', 'PL', 'pl', 'biznes', 69, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'mamstartup', 'MamStartup', 'https://mamstartup.pl/feed/', 'https://mamstartup.pl', 'Startupy', 'PL', 'pl', 'technologia', 70, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'elektroda', 'Elektroda News', 'https://www.elektroda.pl/rtvforum/rss.php', 'https://www.elektroda.pl', 'Elektronika', 'PL', 'pl', 'technologia', 71, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'wylecz-it', 'Instalki.pl', 'https://instalki.pl/feed/', 'https://instalki.pl', 'Oprogramowanie', 'PL', 'pl', 'technologia', 72, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'ai-business-pl', 'Sztuczna Inteligencja', 'https://www.sztucznainteligencja.org.pl/feed/', 'https://www.sztucznainteligencja.org.pl', 'Sztuczna inteligencja', 'PL', 'pl', 'technologia', 73, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'nauka-w-polsce', 'Nauka w Polsce', 'https://naukawpolsce.pl/rss.xml', 'https://naukawpolsce.pl', 'PAP, nauka', 'PL', 'pl', 'nauka', 74, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'crazy-nauka', 'Crazy Nauka', 'https://www.crazynauka.pl/feed/', 'https://www.crazynauka.pl', 'Popularnonaukowy', 'PL', 'pl', 'nauka', 75, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'kopalnia-wiedzy', 'Kopalnia Wiedzy', 'https://kopalniawiedzy.pl/rss.xml', 'https://kopalniawiedzy.pl', 'Popularnonaukowy', 'PL', 'pl', 'nauka', 76, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'focus-pl', 'Focus.pl', 'https://www.focus.pl/feed', 'https://www.focus.pl', 'Popularnonaukowy', 'PL', 'pl', 'nauka', 77, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'national-geographic-pl', 'National Geographic Polska', 'https://www.national-geographic.pl/feed', 'https://www.national-geographic.pl', 'Popularnonaukowy', 'PL', 'pl', 'nauka', 78, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'urania', 'Urania — Postępy Astronomii', 'https://www.urania.edu.pl/rss.xml', 'https://www.urania.edu.pl', 'Astronomia', 'PL', 'pl', 'nauka', 79, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'space24', 'Space24', 'https://space24.pl/_RSS', 'https://space24.pl', 'Kosmos', 'PL', 'pl', 'nauka', 80, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'swiat-nauki', 'Świat Nauki', 'https://www.swiatnauki.pl/feed', 'https://www.swiatnauki.pl', 'Popularnonaukowy', 'PL', 'pl', 'nauka', 81, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'smoglab', 'SmogLab', 'https://smoglab.pl/feed/', 'https://smoglab.pl', 'Klimat i środowisko', 'PL', 'pl', 'nauka', 82, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'nauka-o-klimacie', 'Nauka o klimacie', 'https://naukaoklimacie.pl/feed/', 'https://naukaoklimacie.pl', 'Klimat', 'PL', 'pl', 'nauka', 83, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'ziemia-na-rozdrozu', 'Ziemia na rozdrożu', 'https://ziemianarozdrozu.pl/feed', 'https://ziemianarozdrozu.pl', 'Klimat', 'PL', 'pl', 'nauka', 84, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'przeglad-sportowy', 'Przegląd Sportowy', 'https://przegladsportowy.onet.pl/.feed', 'https://przegladsportowy.onet.pl', 'Sport', 'PL', 'pl', 'sport', 85, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'sport-pl', 'Sport.pl', 'https://www.sport.pl/pub/rss/sport.htm', 'https://www.sport.pl', 'Sport', 'PL', 'pl', 'sport', 86, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'sportowefakty', 'SportoweFakty', 'https://sportowefakty.wp.pl/rss.xml', 'https://sportowefakty.wp.pl', 'Sport', 'PL', 'pl', 'sport', 87, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'meczyki', 'Meczyki.pl', 'https://www.meczyki.pl/rss', 'https://www.meczyki.pl', 'Piłka nożna', 'PL', 'pl', 'sport', 88, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'weszlo', 'Weszło', 'https://weszlo.com/feed/', 'https://weszlo.com', 'Piłka nożna', 'PL', 'pl', 'sport', 89, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'laczynaspilka', 'Łączy nas piłka', 'https://www.laczynaspilka.pl/rss.html', 'https://www.laczynaspilka.pl', 'Reprezentacja', 'PL', 'pl', 'sport', 90, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'polsat-sport', 'Polsat Sport', 'https://www.polsatsport.pl/rss/wszystkie.xml', 'https://www.polsatsport.pl', 'Sport', 'PL', 'pl', 'sport', 91, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'eurosport-pl', 'Eurosport Polska', 'https://www.eurosport.pl/rss.xml', 'https://www.eurosport.pl', 'Sport', 'PL', 'pl', 'sport', 92, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'f1-pl', 'F1 Wyścigi', 'https://f1wyscigi.pl/feed/', 'https://f1wyscigi.pl', 'Formuła 1', 'PL', 'pl', 'sport', 93, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'bieganie-pl', 'Bieganie.pl', 'https://bieganie.pl/feed/', 'https://bieganie.pl', 'Bieganie', 'PL', 'pl', 'sport', 94, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'dwutygodnik', 'Dwutygodnik', 'https://www.dwutygodnik.com/rss.xml', 'https://www.dwutygodnik.com', 'Kultura', 'PL', 'pl', 'kultura', 95, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'culture-pl', 'Culture.pl', 'https://culture.pl/pl/rss.xml', 'https://culture.pl', 'Kultura', 'PL', 'pl', 'kultura', 96, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'filmweb', 'Filmweb — Newsy', 'https://www.filmweb.pl/feed/news/latest', 'https://www.filmweb.pl', 'Film', 'PL', 'pl', 'kultura', 97, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'naekranie', 'naEKRANIE', 'https://naekranie.pl/feed', 'https://naekranie.pl', 'Film i seriale', 'PL', 'pl', 'rozrywka', 98, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'gry-online', 'GRYOnline', 'https://www.gry-online.pl/rss/news.xml', 'https://www.gry-online.pl', 'Gry', 'PL', 'pl', 'rozrywka', 99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'cdaction', 'CD-Action', 'https://cdaction.pl/rss', 'https://cdaction.pl', 'Gry', 'PL', 'pl', 'rozrywka', 100, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("key") DO NOTHING;

-- Wsad 3/9 — kraje: PL, —
INSERT INTO "NewsSourceCatalog" ("id","key","name","rssUrl","homepageUrl","descriptor","country","language","category","sortOrder","createdAt","updatedAt") VALUES
  (gen_random_uuid()::text, 'eurogamer-pl', 'Eurogamer.pl', 'https://www.eurogamer.pl/feed', 'https://www.eurogamer.pl', 'Gry', 'PL', 'pl', 'rozrywka', 101, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'polygamia', 'Polygamia', 'https://polygamia.pl/feed/', 'https://polygamia.pl', 'Gry', 'PL', 'pl', 'rozrywka', 102, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'lubimyczytac', 'Lubimyczytać', 'https://lubimyczytac.pl/rss/wszystkie', 'https://lubimyczytac.pl', 'Książki', 'PL', 'pl', 'kultura', 103, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'dwutygodnik-teatr', 'Teatr dla Was', 'https://teatrdlawas.pl/feed/', 'https://teatrdlawas.pl', 'Teatr', 'PL', 'pl', 'kultura', 104, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'magazyn-pismo', 'Pismo', 'https://magazynpismo.pl/feed/', 'https://magazynpismo.pl', 'Reportaż', 'PL', 'pl', 'kultura', 105, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'audioteka-blog', 'Audiofeel', 'https://audiofeel.pl/feed/', 'https://audiofeel.pl', 'Audio', 'PL', 'pl', 'rozrywka', 106, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'mp-pl', 'Medycyna Praktyczna', 'https://www.mp.pl/rss/rss.php', 'https://www.mp.pl', 'Medycyna', 'PL', 'pl', 'zdrowie', 107, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'rynek-zdrowia', 'Rynek Zdrowia', 'https://www.rynekzdrowia.pl/rss/serwis_rss.xml', 'https://www.rynekzdrowia.pl', 'Ochrona zdrowia', 'PL', 'pl', 'zdrowie', 108, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'pulsmedycyny', 'Puls Medycyny', 'https://pulsmedycyny.pl/rss', 'https://pulsmedycyny.pl', 'Medycyna', 'PL', 'pl', 'zdrowie', 109, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'termedia', 'Termedia', 'https://www.termedia.pl/rss', 'https://www.termedia.pl', 'Medycyna', 'PL', 'pl', 'zdrowie', 110, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'poradnikzdrowie', 'Poradnik Zdrowie', 'https://www.poradnikzdrowie.pl/rss.xml', 'https://www.poradnikzdrowie.pl', 'Zdrowie', 'PL', 'pl', 'zdrowie', 111, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'dietetycy', 'Dietetycy.org.pl', 'https://dietetycy.org.pl/feed/', 'https://dietetycy.org.pl', 'Dietetyka', 'PL', 'pl', 'zdrowie', 112, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'gazeta-krakowska', 'Gazeta Krakowska', 'https://gazetakrakowska.pl/rss.xml', 'https://gazetakrakowska.pl', 'Małopolska', 'PL', 'pl', 'lokalne', 113, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'dziennik-zachodni', 'Dziennik Zachodni', 'https://dziennikzachodni.pl/rss.xml', 'https://dziennikzachodni.pl', 'Śląsk', 'PL', 'pl', 'lokalne', 114, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'dziennik-lodzki', 'Dziennik Łódzki', 'https://dzienniklodzki.pl/rss.xml', 'https://dzienniklodzki.pl', 'Łódzkie', 'PL', 'pl', 'lokalne', 115, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'gazeta-wroclawska', 'Gazeta Wrocławska', 'https://gazetawroclawska.pl/rss.xml', 'https://gazetawroclawska.pl', 'Dolny Śląsk', 'PL', 'pl', 'lokalne', 116, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'kurier-lubelski', 'Kurier Lubelski', 'https://kurierlubelski.pl/rss.xml', 'https://kurierlubelski.pl', 'Lubelskie', 'PL', 'pl', 'lokalne', 117, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'glos-wielkopolski', 'Głos Wielkopolski', 'https://gloswielkopolski.pl/rss.xml', 'https://gloswielkopolski.pl', 'Wielkopolska', 'PL', 'pl', 'lokalne', 118, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'gazeta-pomorska', 'Gazeta Pomorska', 'https://pomorska.pl/rss.xml', 'https://pomorska.pl', 'Kujawsko-pomorskie', 'PL', 'pl', 'lokalne', 119, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'dziennik-baltycki', 'Dziennik Bałtycki', 'https://dziennikbaltycki.pl/rss.xml', 'https://dziennikbaltycki.pl', 'Pomorze', 'PL', 'pl', 'lokalne', 120, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'echo-dnia', 'Echo Dnia', 'https://echodnia.eu/rss.xml', 'https://echodnia.eu', 'Świętokrzyskie', 'PL', 'pl', 'lokalne', 121, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'nowiny24', 'Nowiny24', 'https://nowiny24.pl/rss.xml', 'https://nowiny24.pl', 'Podkarpacie', 'PL', 'pl', 'lokalne', 122, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'kurier-poranny', 'Kurier Poranny', 'https://poranny.pl/rss.xml', 'https://poranny.pl', 'Podlasie', 'PL', 'pl', 'lokalne', 123, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'gazeta-lubuska', 'Gazeta Lubuska', 'https://gazetalubuska.pl/rss.xml', 'https://gazetalubuska.pl', 'Lubuskie', 'PL', 'pl', 'lokalne', 124, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'glos-szczecinski', 'Głos Szczeciński', 'https://gs24.pl/rss.xml', 'https://gs24.pl', 'Zachodniopomorskie', 'PL', 'pl', 'lokalne', 125, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'gazeta-olsztynska', 'Gazeta Olsztyńska', 'https://gazetaolsztynska.pl/rss.xml', 'https://gazetaolsztynska.pl', 'Warmia i Mazury', 'PL', 'pl', 'lokalne', 126, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'warszawa-naszemiasto', 'Nasze Miasto Warszawa', 'https://warszawa.naszemiasto.pl/rss.xml', 'https://warszawa.naszemiasto.pl', 'Warszawa', 'PL', 'pl', 'lokalne', 127, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'tvp-warszawa', 'Radio dla Ciebie', 'https://www.rdc.pl/feed/', 'https://www.rdc.pl', 'Mazowsze', 'PL', 'pl', 'lokalne', 128, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'trojmiasto', 'Trojmiasto.pl', 'https://www.trojmiasto.pl/rss/', 'https://www.trojmiasto.pl', 'Trójmiasto', 'PL', 'pl', 'lokalne', 129, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'lodz-tuLodz', 'TuLodz', 'https://tulodz.pl/feed/', 'https://tulodz.pl', 'Łódź', 'PL', 'pl', 'lokalne', 130, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'poznan-epoznan', 'epoznan.pl', 'https://epoznan.pl/rss', 'https://epoznan.pl', 'Poznań', 'PL', 'pl', 'lokalne', 131, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'krakow-lovekrakow', 'LoveKraków', 'https://lovekrakow.pl/rss', 'https://lovekrakow.pl', 'Kraków', 'PL', 'pl', 'lokalne', 132, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-reuters-world', 'Reuters — World', 'https://www.reutersagency.com/feed/?best-topics=world&post_type=best', 'https://www.reuters.com', 'Agencja prasowa', '', 'en', 'wiadomosci', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-ap-top', 'Associated Press — Top News', 'https://rsshub.app/apnews/topics/apf-topnews', 'https://apnews.com', 'Agencja prasowa', '', 'en', 'wiadomosci', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-afp-english', 'France 24 — World', 'https://www.france24.com/en/rss', 'https://www.france24.com/en', 'Telewizja publiczna', '', 'en', 'wiadomosci', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-un-news', 'UN News', 'https://news.un.org/feed/subscribe/en/news/all/rss.xml', 'https://news.un.org', 'ONZ', '', 'en', 'wiadomosci', 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-euronews', 'Euronews', 'https://www.euronews.com/rss', 'https://www.euronews.com', 'Europa', '', 'en', 'wiadomosci', 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-politico-eu', 'Politico Europe', 'https://www.politico.eu/feed/', 'https://www.politico.eu', 'Polityka europejska', '', 'en', 'wiadomosci', 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-economist-latest', 'The Economist — Latest', 'https://www.economist.com/latest/rss.xml', 'https://www.economist.com', 'Tygodnik, liberalny', '', 'en', 'opinie', 7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-foreign-policy', 'Foreign Policy', 'https://foreignpolicy.com/feed/', 'https://foreignpolicy.com', 'Stosunki międzynarodowe', '', 'en', 'opinie', 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-foreign-affairs', 'Foreign Affairs', 'https://www.foreignaffairs.com/rss.xml', 'https://www.foreignaffairs.com', 'Stosunki międzynarodowe', '', 'en', 'opinie', 9, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-defense-one', 'Defense One', 'https://www.defenseone.com/rss/all/', 'https://www.defenseone.com', 'Obronność', '', 'en', 'wiadomosci', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-war-on-the-rocks', 'War on the Rocks', 'https://warontherocks.com/feed/', 'https://warontherocks.com', 'Bezpieczeństwo', '', 'en', 'opinie', 11, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-carnegie', 'Carnegie Endowment', 'https://carnegieendowment.org/rss/all.xml', 'https://carnegieendowment.org', 'Think tank', '', 'en', 'opinie', 12, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-brookings', 'Brookings', 'https://www.brookings.edu/feed/', 'https://www.brookings.edu', 'Think tank', '', 'en', 'opinie', 13, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-chatham-house', 'Chatham House', 'https://www.chathamhouse.org/rss/all', 'https://www.chathamhouse.org', 'Think tank', '', 'en', 'opinie', 14, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-ecfr', 'European Council on Foreign Relations', 'https://ecfr.eu/feed/', 'https://ecfr.eu', 'Think tank', '', 'en', 'opinie', 15, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-bruegel', 'Bruegel', 'https://www.bruegel.org/rss.xml', 'https://www.bruegel.org', 'Ekonomia europejska', '', 'en', 'biznes', 16, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-imf-blog', 'IMF Blog', 'https://www.imf.org/en/Blogs/rss', 'https://www.imf.org/en/Blogs', 'Międzynarodowy Fundusz Walutowy', '', 'en', 'biznes', 17, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-world-bank', 'World Bank — News', 'https://www.worldbank.org/en/news/all.rss', 'https://www.worldbank.org', 'Bank Światowy', '', 'en', 'biznes', 18, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("key") DO NOTHING;

-- Wsad 4/9 — kraje: US, —
INSERT INTO "NewsSourceCatalog" ("id","key","name","rssUrl","homepageUrl","descriptor","country","language","category","sortOrder","createdAt","updatedAt") VALUES
  (gen_random_uuid()::text, 'intl-oecd', 'OECD', 'https://www.oecd.org/newsroom/index.xml', 'https://www.oecd.org', 'OECD', '', 'en', 'biznes', 19, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-who', 'World Health Organization', 'https://www.who.int/rss-feeds/news-english.xml', 'https://www.who.int', 'Zdrowie publiczne', '', 'en', 'zdrowie', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-ecdc', 'ECDC', 'https://www.ecdc.europa.eu/en/rss', 'https://www.ecdc.europa.eu', 'Epidemiologia UE', '', 'en', 'zdrowie', 21, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-nature', 'Nature', 'https://www.nature.com/nature.rss', 'https://www.nature.com', 'Czasopismo naukowe', '', 'en', 'nauka', 22, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-science-mag', 'Science', 'https://www.science.org/rss/news_current.xml', 'https://www.science.org', 'Czasopismo naukowe', '', 'en', 'nauka', 23, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-nature-briefing', 'Nature — Research Highlights', 'https://www.nature.com/nature/articles?type=research-highlight.rss', 'https://www.nature.com', 'Czasopismo naukowe', '', 'en', 'nauka', 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-arxiv-cs-ai', 'arXiv — sztuczna inteligencja', 'https://rss.arxiv.org/rss/cs.AI', 'https://arxiv.org/list/cs.AI/recent', 'Preprinty', '', 'en', 'nauka', 25, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-arxiv-cs-lg', 'arXiv — uczenie maszynowe', 'https://rss.arxiv.org/rss/cs.LG', 'https://arxiv.org/list/cs.LG/recent', 'Preprinty', '', 'en', 'nauka', 26, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-arxiv-astro-ph', 'arXiv — astrofizyka', 'https://rss.arxiv.org/rss/astro-ph', 'https://arxiv.org/list/astro-ph/recent', 'Preprinty', '', 'en', 'nauka', 27, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-arxiv-cond-mat', 'arXiv — materia skondensowana', 'https://rss.arxiv.org/rss/cond-mat', 'https://arxiv.org/list/cond-mat/recent', 'Preprinty', '', 'en', 'nauka', 28, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-phys-org', 'Phys.org', 'https://phys.org/rss-feed/', 'https://phys.org', 'Popularnonaukowy', '', 'en', 'nauka', 29, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-eurekalert', 'EurekAlert!', 'https://www.eurekalert.org/rss/technology_engineering.xml', 'https://www.eurekalert.org', 'Komunikaty naukowe', '', 'en', 'nauka', 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-quanta', 'Quanta Magazine', 'https://api.quantamagazine.org/feed/', 'https://www.quantamagazine.org', 'Nauka pogłębiona', '', 'en', 'nauka', 31, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-nasa-breaking', 'NASA — Breaking News', 'https://www.nasa.gov/rss/dyn/breaking_news.rss', 'https://www.nasa.gov', 'Agencja kosmiczna', '', 'en', 'nauka', 32, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-nasa-image', 'NASA — Image of the Day', 'https://www.nasa.gov/rss/dyn/lg_image_of_the_day.rss', 'https://www.nasa.gov', 'Agencja kosmiczna', '', 'en', 'nauka', 33, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-esa', 'ESA — Space News', 'https://www.esa.int/rssfeed/Our_Activities/Space_News', 'https://www.esa.int', 'Europejska Agencja Kosmiczna', '', 'en', 'nauka', 34, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-spacenews', 'SpaceNews', 'https://spacenews.com/feed/', 'https://spacenews.com', 'Przemysł kosmiczny', '', 'en', 'nauka', 35, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-space-com', 'Space.com', 'https://www.space.com/feeds/all', 'https://www.space.com', 'Kosmos', '', 'en', 'nauka', 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-nasa-jpl', 'NASA JPL', 'https://www.jpl.nasa.gov/feeds/news', 'https://www.jpl.nasa.gov', 'Laboratorium napędu odrzutowego', '', 'en', 'nauka', 37, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-sky-telescope', 'Sky & Telescope', 'https://skyandtelescope.org/feed/', 'https://skyandtelescope.org', 'Astronomia', '', 'en', 'nauka', 38, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-hackernews', 'Hacker News — Front Page', 'https://hnrss.org/frontpage', 'https://news.ycombinator.com', 'Technologia, agregator', '', 'en', 'technologia', 39, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-lobsters', 'Lobsters', 'https://lobste.rs/rss', 'https://lobste.rs', 'Technologia, agregator', '', 'en', 'technologia', 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-github-blog', 'GitHub Blog', 'https://github.blog/feed/', 'https://github.blog', 'Programowanie', '', 'en', 'technologia', 41, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-stackoverflow-blog', 'Stack Overflow Blog', 'https://stackoverflow.blog/feed/', 'https://stackoverflow.blog', 'Programowanie', '', 'en', 'technologia', 42, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-mozilla-hacks', 'Mozilla Hacks', 'https://hacks.mozilla.org/feed/', 'https://hacks.mozilla.org', 'Web', '', 'en', 'technologia', 43, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-web-dev', 'web.dev', 'https://web.dev/static/blog/feed.xml', 'https://web.dev', 'Web', '', 'en', 'technologia', 44, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-css-tricks', 'CSS-Tricks', 'https://css-tricks.com/feed/', 'https://css-tricks.com', 'Frontend', '', 'en', 'technologia', 45, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-smashing', 'Smashing Magazine', 'https://www.smashingmagazine.com/feed/', 'https://www.smashingmagazine.com', 'Frontend', '', 'en', 'technologia', 46, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-infoq', 'InfoQ', 'https://feed.infoq.com/', 'https://www.infoq.com', 'Inżynieria oprogramowania', '', 'en', 'technologia', 47, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-thoughtworks', 'Martin Fowler', 'https://martinfowler.com/feed.atom', 'https://martinfowler.com', 'Architektura oprogramowania', '', 'en', 'technologia', 48, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-lwn', 'LWN.net', 'https://lwn.net/headlines/newrss', 'https://lwn.net', 'Linux', '', 'en', 'technologia', 49, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-phoronix', 'Phoronix', 'https://www.phoronix.com/rss.php', 'https://www.phoronix.com', 'Linux i sprzęt', '', 'en', 'technologia', 50, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-krebs', 'Krebs on Security', 'https://krebsonsecurity.com/feed/', 'https://krebsonsecurity.com', 'Bezpieczeństwo', '', 'en', 'technologia', 51, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-schneier', 'Schneier on Security', 'https://www.schneier.com/feed/atom/', 'https://www.schneier.com', 'Bezpieczeństwo', '', 'en', 'technologia', 52, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-bleepingcomputer', 'BleepingComputer', 'https://www.bleepingcomputer.com/feed/', 'https://www.bleepingcomputer.com', 'Bezpieczeństwo', '', 'en', 'technologia', 53, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-hacker-news-thn', 'The Hacker News', 'https://feeds.feedburner.com/TheHackersNews', 'https://thehackernews.com', 'Bezpieczeństwo', '', 'en', 'technologia', 54, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-darkreading', 'Dark Reading', 'https://www.darkreading.com/rss.xml', 'https://www.darkreading.com', 'Bezpieczeństwo', '', 'en', 'technologia', 55, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-cisa', 'CISA — Alerts', 'https://www.cisa.gov/cybersecurity-advisories/all.xml', 'https://www.cisa.gov', 'Ostrzeżenia bezpieczeństwa', '', 'en', 'technologia', 56, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-openai-blog', 'OpenAI Blog', 'https://openai.com/news/rss.xml', 'https://openai.com/news', 'Sztuczna inteligencja', '', 'en', 'technologia', 57, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-deepmind', 'Google DeepMind', 'https://deepmind.google/blog/rss.xml', 'https://deepmind.google/discover/blog', 'Sztuczna inteligencja', '', 'en', 'technologia', 58, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-huggingface', 'Hugging Face Blog', 'https://huggingface.co/blog/feed.xml', 'https://huggingface.co/blog', 'Sztuczna inteligencja', '', 'en', 'technologia', 59, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-import-ai', 'Import AI', 'https://importai.substack.com/feed', 'https://importai.substack.com', 'Sztuczna inteligencja', '', 'en', 'technologia', 60, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-mit-tech-review', 'MIT Technology Review', 'https://www.technologyreview.com/feed/', 'https://www.technologyreview.com', 'Technologia', '', 'en', 'technologia', 61, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-ieee-spectrum', 'IEEE Spectrum', 'https://spectrum.ieee.org/feeds/feed.rss', 'https://spectrum.ieee.org', 'Inżynieria', '', 'en', 'technologia', 62, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-tldr', 'TLDR Newsletter', 'https://tldr.tech/api/rss/tech', 'https://tldr.tech', 'Technologia, skrót', '', 'en', 'technologia', 63, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-nytimes-home', 'The New York Times — Home', 'https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml', 'https://www.nytimes.com', 'Dziennik, lewa strona centrum', 'US', 'en', 'wiadomosci', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-nytimes-world', 'The New York Times — World', 'https://rss.nytimes.com/services/xml/rss/nyt/World.xml', 'https://www.nytimes.com/section/world', 'Dziennik', 'US', 'en', 'wiadomosci', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-nytimes-tech', 'The New York Times — Technology', 'https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml', 'https://www.nytimes.com/section/technology', 'Dziennik, technologia', 'US', 'en', 'technologia', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-washingtonpost-world', 'The Washington Post — World', 'https://feeds.washingtonpost.com/rss/world', 'https://www.washingtonpost.com', 'Dziennik, lewa strona centrum', 'US', 'en', 'wiadomosci', 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-wsj-world', 'The Wall Street Journal — World', 'https://feeds.a.dj.com/rss/RSSWorldNews.xml', 'https://www.wsj.com', 'Dziennik, prawa strona centrum', 'US', 'en', 'wiadomosci', 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("key") DO NOTHING;

-- Wsad 5/9 — kraje: US
INSERT INTO "NewsSourceCatalog" ("id","key","name","rssUrl","homepageUrl","descriptor","country","language","category","sortOrder","createdAt","updatedAt") VALUES
  (gen_random_uuid()::text, 'us-wsj-markets', 'The Wall Street Journal — Markets', 'https://feeds.a.dj.com/rss/RSSMarketsMain.xml', 'https://www.wsj.com/finance', 'Rynki', 'US', 'en', 'biznes', 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-npr', 'NPR — News', 'https://feeds.npr.org/1001/rss.xml', 'https://www.npr.org', 'Radio publiczne', 'US', 'en', 'wiadomosci', 7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-pbs-newshour', 'PBS NewsHour', 'https://www.pbs.org/newshour/feeds/rss/headlines', 'https://www.pbs.org/newshour', 'Telewizja publiczna', 'US', 'en', 'wiadomosci', 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-cnn-top', 'CNN — Top Stories', 'http://rss.cnn.com/rss/edition.rss', 'https://edition.cnn.com', 'Telewizja informacyjna', 'US', 'en', 'wiadomosci', 9, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-cbs-news', 'CBS News', 'https://www.cbsnews.com/latest/rss/main', 'https://www.cbsnews.com', 'Telewizja', 'US', 'en', 'wiadomosci', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-abc-news', 'ABC News', 'https://abcnews.go.com/abcnews/topstories', 'https://abcnews.go.com', 'Telewizja', 'US', 'en', 'wiadomosci', 11, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-nbc-news', 'NBC News', 'https://feeds.nbcnews.com/nbcnews/public/news', 'https://www.nbcnews.com', 'Telewizja', 'US', 'en', 'wiadomosci', 12, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-fox-news', 'Fox News', 'https://moxie.foxnews.com/google-publisher/latest.xml', 'https://www.foxnews.com', 'Telewizja, prawa strona', 'US', 'en', 'wiadomosci', 13, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-usa-today', 'USA Today', 'https://rssfeeds.usatoday.com/usatoday-NewsTopStories', 'https://www.usatoday.com', 'Dziennik', 'US', 'en', 'wiadomosci', 14, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-la-times', 'Los Angeles Times', 'https://www.latimes.com/rss2.0.xml', 'https://www.latimes.com', 'Dziennik', 'US', 'en', 'wiadomosci', 15, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-politico', 'Politico', 'https://rss.politico.com/politics-news.xml', 'https://www.politico.com', 'Polityka', 'US', 'en', 'wiadomosci', 16, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-the-hill', 'The Hill', 'https://thehill.com/feed/', 'https://thehill.com', 'Polityka', 'US', 'en', 'wiadomosci', 17, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-axios', 'Axios', 'https://api.axios.com/feed/', 'https://www.axios.com', 'Skrótowy', 'US', 'en', 'wiadomosci', 18, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-propublica', 'ProPublica', 'https://www.propublica.org/feeds/propublica/main', 'https://www.propublica.org', 'Dziennikarstwo śledcze', 'US', 'en', 'opinie', 19, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-the-atlantic', 'The Atlantic', 'https://www.theatlantic.com/feed/all/', 'https://www.theatlantic.com', 'Magazyn', 'US', 'en', 'opinie', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-the-new-yorker', 'The New Yorker', 'https://www.newyorker.com/feed/everything', 'https://www.newyorker.com', 'Magazyn', 'US', 'en', 'kultura', 21, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-vox', 'Vox', 'https://www.vox.com/rss/index.xml', 'https://www.vox.com', 'Wyjaśniający, lewa strona', 'US', 'en', 'opinie', 22, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-slate', 'Slate', 'https://slate.com/feeds/all.rss', 'https://slate.com', 'Magazyn, lewa strona', 'US', 'en', 'opinie', 23, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-reason', 'Reason', 'https://reason.com/feed/', 'https://reason.com', 'Libertariański', 'US', 'en', 'opinie', 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-national-review', 'National Review', 'https://www.nationalreview.com/feed/', 'https://www.nationalreview.com', 'Konserwatywny', 'US', 'en', 'opinie', 25, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-the-dispatch', 'The Dispatch', 'https://thedispatch.com/feed/', 'https://thedispatch.com', 'Konserwatywny, centrowy', 'US', 'en', 'opinie', 26, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-bloomberg-markets', 'Bloomberg — Markets', 'https://feeds.bloomberg.com/markets/news.rss', 'https://www.bloomberg.com/markets', 'Rynki finansowe', 'US', 'en', 'biznes', 27, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-bloomberg-tech', 'Bloomberg — Technology', 'https://feeds.bloomberg.com/technology/news.rss', 'https://www.bloomberg.com/technology', 'Technologia', 'US', 'en', 'technologia', 28, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-cnbc-top', 'CNBC — Top News', 'https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=100003114', 'https://www.cnbc.com', 'Telewizja biznesowa', 'US', 'en', 'biznes', 29, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-marketwatch', 'MarketWatch', 'https://feeds.content.dowjones.io/public/rss/mw_topstories', 'https://www.marketwatch.com', 'Rynki', 'US', 'en', 'biznes', 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-fortune', 'Fortune', 'https://fortune.com/feed/', 'https://fortune.com', 'Biznes', 'US', 'en', 'biznes', 31, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-forbes', 'Forbes', 'https://www.forbes.com/real-time/feed2/', 'https://www.forbes.com', 'Biznes', 'US', 'en', 'biznes', 32, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-harvard-business-review', 'Harvard Business Review', 'https://feeds.hbr.org/harvardbusiness', 'https://hbr.org', 'Zarządzanie', 'US', 'en', 'biznes', 33, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-federal-reserve', 'Federal Reserve — Press', 'https://www.federalreserve.gov/feeds/press_all.xml', 'https://www.federalreserve.gov', 'Bank centralny', 'US', 'en', 'biznes', 34, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-techcrunch', 'TechCrunch', 'https://techcrunch.com/feed/', 'https://techcrunch.com', 'Startupy', 'US', 'en', 'technologia', 35, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-ars-technica', 'Ars Technica', 'https://feeds.arstechnica.com/arstechnica/index', 'https://arstechnica.com', 'Technologia pogłębiona', 'US', 'en', 'technologia', 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-the-verge', 'The Verge', 'https://www.theverge.com/rss/index.xml', 'https://www.theverge.com', 'Technologia', 'US', 'en', 'technologia', 37, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-wired', 'WIRED', 'https://www.wired.com/feed/rss', 'https://www.wired.com', 'Technologia', 'US', 'en', 'technologia', 38, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-engadget', 'Engadget', 'https://www.engadget.com/rss.xml', 'https://www.engadget.com', 'Sprzęt', 'US', 'en', 'technologia', 39, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-9to5mac', '9to5Mac', 'https://9to5mac.com/feed/', 'https://9to5mac.com', 'Apple', 'US', 'en', 'technologia', 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-9to5google', '9to5Google', 'https://9to5google.com/feed/', 'https://9to5google.com', 'Google', 'US', 'en', 'technologia', 41, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-anandtech', 'AnandTech', 'https://www.anandtech.com/rss/', 'https://www.anandtech.com', 'Sprzęt', 'US', 'en', 'technologia', 42, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-tomshardware', 'Tom''s Hardware', 'https://www.tomshardware.com/feeds/all', 'https://www.tomshardware.com', 'Sprzęt', 'US', 'en', 'technologia', 43, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-servethehome', 'ServeTheHome', 'https://www.servethehome.com/feed/', 'https://www.servethehome.com', 'Serwery', 'US', 'en', 'technologia', 44, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-hackaday', 'Hackaday', 'https://hackaday.com/feed/', 'https://hackaday.com', 'Elektronika i DIY', 'US', 'en', 'technologia', 45, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-adafruit', 'Adafruit Blog', 'https://blog.adafruit.com/feed/', 'https://blog.adafruit.com', 'Elektronika i DIY', 'US', 'en', 'technologia', 46, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-aws-blog', 'AWS News Blog', 'https://aws.amazon.com/blogs/aws/feed/', 'https://aws.amazon.com/blogs/aws', 'Chmura', 'US', 'en', 'technologia', 47, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-google-cloud-blog', 'Google Cloud Blog', 'https://cloudblog.withgoogle.com/rss/', 'https://cloud.google.com/blog', 'Chmura', 'US', 'en', 'technologia', 48, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-microsoft-devblogs', 'Microsoft DevBlogs', 'https://devblogs.microsoft.com/feed/', 'https://devblogs.microsoft.com', 'Programowanie', 'US', 'en', 'technologia', 49, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-scientific-american', 'Scientific American', 'https://www.scientificamerican.com/platform/syndication/rss/', 'https://www.scientificamerican.com', 'Popularnonaukowy', 'US', 'en', 'nauka', 50, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-smithsonian', 'Smithsonian Magazine', 'https://www.smithsonianmag.com/rss/latest_articles/', 'https://www.smithsonianmag.com', 'Popularnonaukowy', 'US', 'en', 'nauka', 51, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-nat-geo', 'National Geographic', 'https://www.nationalgeographic.com/pages/feed/rss', 'https://www.nationalgeographic.com', 'Popularnonaukowy', 'US', 'en', 'nauka', 52, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-noaa', 'NOAA — News', 'https://www.noaa.gov/rss.xml', 'https://www.noaa.gov', 'Klimat i oceany', 'US', 'en', 'nauka', 53, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-usgs-quakes', 'USGS — Trzęsienia ziemi', 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/significant_week.atom', 'https://earthquake.usgs.gov', 'Sejsmologia', 'US', 'en', 'nauka', 54, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-statnews', 'STAT News', 'https://www.statnews.com/feed/', 'https://www.statnews.com', 'Medycyna i biotechnologia', 'US', 'en', 'zdrowie', 55, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("key") DO NOTHING;

-- Wsad 6/9 — kraje: DE, GB, IE, US
INSERT INTO "NewsSourceCatalog" ("id","key","name","rssUrl","homepageUrl","descriptor","country","language","category","sortOrder","createdAt","updatedAt") VALUES
  (gen_random_uuid()::text, 'us-kff-health', 'KFF Health News', 'https://kffhealthnews.org/feed/', 'https://kffhealthnews.org', 'Ochrona zdrowia', 'US', 'en', 'zdrowie', 56, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-nejm', 'New England Journal of Medicine', 'https://www.nejm.org/action/showFeed?type=etoc&feed=rss&jc=nejm', 'https://www.nejm.org', 'Czasopismo medyczne', 'US', 'en', 'zdrowie', 57, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-espn', 'ESPN — Top Headlines', 'https://www.espn.com/espn/rss/news', 'https://www.espn.com', 'Sport', 'US', 'en', 'sport', 58, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-the-athletic', 'The Athletic', 'https://theathletic.com/rss/', 'https://theathletic.com', 'Sport pogłębiony', 'US', 'en', 'sport', 59, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-variety', 'Variety', 'https://variety.com/feed/', 'https://variety.com', 'Rozrywka', 'US', 'en', 'rozrywka', 60, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-hollywood-reporter', 'The Hollywood Reporter', 'https://www.hollywoodreporter.com/feed/', 'https://www.hollywoodreporter.com', 'Rozrywka', 'US', 'en', 'rozrywka', 61, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-pitchfork', 'Pitchfork', 'https://pitchfork.com/feed/feed-news/rss', 'https://pitchfork.com', 'Muzyka', 'US', 'en', 'kultura', 62, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-rolling-stone', 'Rolling Stone', 'https://www.rollingstone.com/feed/', 'https://www.rollingstone.com', 'Muzyka i kultura', 'US', 'en', 'kultura', 63, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-ign', 'IGN', 'https://feeds.ign.com/ign/all', 'https://www.ign.com', 'Gry', 'US', 'en', 'rozrywka', 64, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-polygon', 'Polygon', 'https://www.polygon.com/rss/index.xml', 'https://www.polygon.com', 'Gry', 'US', 'en', 'rozrywka', 65, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-kotaku', 'Kotaku', 'https://kotaku.com/rss', 'https://kotaku.com', 'Gry', 'US', 'en', 'rozrywka', 66, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-gamespot', 'GameSpot', 'https://www.gamespot.com/feeds/mashup/', 'https://www.gamespot.com', 'Gry', 'US', 'en', 'rozrywka', 67, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-paris-review', 'The Paris Review', 'https://www.theparisreview.org/blog/feed/', 'https://www.theparisreview.org', 'Literatura', 'US', 'en', 'kultura', 68, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-lithub', 'Literary Hub', 'https://lithub.com/feed/', 'https://lithub.com', 'Literatura', 'US', 'en', 'kultura', 69, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-serious-eats', 'Serious Eats', 'https://www.seriouseats.com/rss', 'https://www.seriouseats.com', 'Kuchnia', 'US', 'en', 'rozrywka', 70, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'us-nyt-cooking', 'NYT — Food', 'https://rss.nytimes.com/services/xml/rss/nyt/DiningandWine.xml', 'https://www.nytimes.com/section/food', 'Kuchnia', 'US', 'en', 'rozrywka', 71, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'gb-bbc-world', 'BBC News — World', 'https://feeds.bbci.co.uk/news/world/rss.xml', 'https://www.bbc.com/news/world', 'Nadawca publiczny', 'GB', 'en', 'wiadomosci', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'gb-bbc-top', 'BBC News — Top Stories', 'https://feeds.bbci.co.uk/news/rss.xml', 'https://www.bbc.com/news', 'Nadawca publiczny', 'GB', 'en', 'wiadomosci', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'gb-bbc-tech', 'BBC News — Technology', 'https://feeds.bbci.co.uk/news/technology/rss.xml', 'https://www.bbc.com/news/technology', 'Nadawca publiczny', 'GB', 'en', 'technologia', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'gb-bbc-science', 'BBC News — Science', 'https://feeds.bbci.co.uk/news/science_and_environment/rss.xml', 'https://www.bbc.com/news/science_and_environment', 'Nadawca publiczny', 'GB', 'en', 'nauka', 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'gb-guardian-world', 'The Guardian — World', 'https://www.theguardian.com/world/rss', 'https://www.theguardian.com/world', 'Dziennik, lewa strona', 'GB', 'en', 'wiadomosci', 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'gb-guardian-uk', 'The Guardian — UK', 'https://www.theguardian.com/uk/rss', 'https://www.theguardian.com/uk', 'Dziennik, lewa strona', 'GB', 'en', 'wiadomosci', 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'gb-guardian-tech', 'The Guardian — Technology', 'https://www.theguardian.com/uk/technology/rss', 'https://www.theguardian.com/uk/technology', 'Dziennik', 'GB', 'en', 'technologia', 7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'gb-guardian-science', 'The Guardian — Science', 'https://www.theguardian.com/science/rss', 'https://www.theguardian.com/science', 'Dziennik', 'GB', 'en', 'nauka', 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'gb-telegraph', 'The Telegraph', 'https://www.telegraph.co.uk/news/rss.xml', 'https://www.telegraph.co.uk', 'Dziennik, prawa strona', 'GB', 'en', 'wiadomosci', 9, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'gb-times', 'The Times', 'https://www.thetimes.co.uk/rss', 'https://www.thetimes.co.uk', 'Dziennik, prawa strona centrum', 'GB', 'en', 'wiadomosci', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'gb-independent', 'The Independent', 'https://www.independent.co.uk/news/rss', 'https://www.independent.co.uk', 'Dziennik', 'GB', 'en', 'wiadomosci', 11, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'gb-sky-news', 'Sky News', 'https://feeds.skynews.com/feeds/rss/world.xml', 'https://news.sky.com', 'Telewizja informacyjna', 'GB', 'en', 'wiadomosci', 12, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'gb-ft-home', 'Financial Times', 'https://www.ft.com/rss/home', 'https://www.ft.com', 'Dziennik finansowy', 'GB', 'en', 'biznes', 13, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'gb-economist-finance', 'The Economist — Finance', 'https://www.economist.com/finance-and-economics/rss.xml', 'https://www.economist.com/finance-and-economics', 'Tygodnik', 'GB', 'en', 'biznes', 14, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'gb-spectator', 'The Spectator', 'https://www.spectator.co.uk/feed', 'https://www.spectator.co.uk', 'Konserwatywny', 'GB', 'en', 'opinie', 15, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'gb-new-statesman', 'New Statesman', 'https://www.newstatesman.com/feed', 'https://www.newstatesman.com', 'Lewa strona', 'GB', 'en', 'opinie', 16, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'gb-unherd', 'UnHerd', 'https://unherd.com/feed/', 'https://unherd.com', 'Heterodoksyjny', 'GB', 'en', 'opinie', 17, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'gb-register', 'The Register', 'https://www.theregister.com/headlines.atom', 'https://www.theregister.com', 'Technologia, ironiczny', 'GB', 'en', 'technologia', 18, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'gb-new-scientist', 'New Scientist', 'https://www.newscientist.com/feed/home/', 'https://www.newscientist.com', 'Popularnonaukowy', 'GB', 'en', 'nauka', 19, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'gb-nature-astronomy', 'Nature Astronomy', 'https://www.nature.com/natastron.rss', 'https://www.nature.com/natastron', 'Czasopismo naukowe', 'GB', 'en', 'nauka', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'gb-lancet', 'The Lancet', 'https://www.thelancet.com/rssfeed/lancet_current.xml', 'https://www.thelancet.com', 'Czasopismo medyczne', 'GB', 'en', 'zdrowie', 21, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'gb-bmj', 'The BMJ', 'https://www.bmj.com/rss/recent.xml', 'https://www.bmj.com', 'Czasopismo medyczne', 'GB', 'en', 'zdrowie', 22, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'gb-bbc-sport', 'BBC Sport', 'https://feeds.bbci.co.uk/sport/rss.xml', 'https://www.bbc.com/sport', 'Sport', 'GB', 'en', 'sport', 23, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'gb-eurosport', 'Eurosport UK', 'https://www.eurosport.com/rss.xml', 'https://www.eurosport.com', 'Sport', 'GB', 'en', 'sport', 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'gb-autosport', 'Autosport', 'https://www.autosport.com/rss/feed/all', 'https://www.autosport.com', 'Sporty motorowe', 'GB', 'en', 'sport', 25, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'gb-eurogamer', 'Eurogamer', 'https://www.eurogamer.net/feed', 'https://www.eurogamer.net', 'Gry', 'GB', 'en', 'rozrywka', 26, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'gb-rock-paper-shotgun', 'Rock Paper Shotgun', 'https://www.rockpapershotgun.com/feed', 'https://www.rockpapershotgun.com', 'Gry', 'GB', 'en', 'rozrywka', 27, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'gb-nme', 'NME', 'https://www.nme.com/feed', 'https://www.nme.com', 'Muzyka', 'GB', 'en', 'kultura', 28, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'gb-lrb', 'London Review of Books', 'https://www.lrb.co.uk/feeds/rss', 'https://www.lrb.co.uk', 'Literatura', 'GB', 'en', 'kultura', 29, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'gb-bank-of-england', 'Bank of England', 'https://www.bankofengland.co.uk/rss/news', 'https://www.bankofengland.co.uk', 'Bank centralny', 'GB', 'en', 'biznes', 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'ie-irish-times', 'The Irish Times', 'https://www.irishtimes.com/arc/outboundfeeds/feed-rss/', 'https://www.irishtimes.com', 'Dziennik', 'IE', 'en', 'wiadomosci', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'ie-rte', 'RTÉ News', 'https://www.rte.ie/feeds/rss/?index=/news/', 'https://www.rte.ie/news', 'Nadawca publiczny', 'IE', 'en', 'wiadomosci', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'ie-journal', 'TheJournal.ie', 'https://www.thejournal.ie/feed/', 'https://www.thejournal.ie', 'Serwis informacyjny', 'IE', 'en', 'wiadomosci', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'de-spiegel', 'Der Spiegel', 'https://www.spiegel.de/schlagzeilen/index.rss', 'https://www.spiegel.de', 'Tygodnik, lewa strona centrum', 'DE', 'de', 'wiadomosci', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("key") DO NOTHING;

-- Wsad 7/9 — kraje: AT, BE, CH, DE, ES, FR, IT, NL, PT
INSERT INTO "NewsSourceCatalog" ("id","key","name","rssUrl","homepageUrl","descriptor","country","language","category","sortOrder","createdAt","updatedAt") VALUES
  (gen_random_uuid()::text, 'de-zeit', 'Die Zeit', 'https://newsfeed.zeit.de/index', 'https://www.zeit.de', 'Tygodnik, liberalny', 'DE', 'de', 'wiadomosci', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'de-faz', 'Frankfurter Allgemeine', 'https://www.faz.net/rss/aktuell/', 'https://www.faz.net', 'Dziennik, prawa strona centrum', 'DE', 'de', 'wiadomosci', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'de-sueddeutsche', 'Süddeutsche Zeitung', 'https://rss.sueddeutsche.de/rss/Topthemen', 'https://www.sueddeutsche.de', 'Dziennik, lewa strona centrum', 'DE', 'de', 'wiadomosci', 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'de-welt', 'Die Welt', 'https://www.welt.de/feeds/latest.rss', 'https://www.welt.de', 'Dziennik, prawa strona', 'DE', 'de', 'wiadomosci', 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'de-taz', 'taz', 'https://taz.de/!p4608;rss/', 'https://taz.de', 'Lewa strona', 'DE', 'de', 'wiadomosci', 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'de-tagesschau', 'tagesschau', 'https://www.tagesschau.de/index~rss2.xml', 'https://www.tagesschau.de', 'Nadawca publiczny', 'DE', 'de', 'wiadomosci', 7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'de-dw-de', 'Deutsche Welle', 'https://rss.dw.com/rdf/rss-de-all', 'https://www.dw.com/de', 'Nadawca zagraniczny', 'DE', 'de', 'wiadomosci', 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'de-dw-en', 'Deutsche Welle — English', 'https://rss.dw.com/rdf/rss-en-all', 'https://www.dw.com/en', 'Nadawca zagraniczny', 'DE', 'en', 'wiadomosci', 9, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'de-handelsblatt', 'Handelsblatt', 'https://www.handelsblatt.com/contentexport/feed/schlagzeilen', 'https://www.handelsblatt.com', 'Dziennik gospodarczy', 'DE', 'de', 'biznes', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'de-heise', 'heise online', 'https://www.heise.de/rss/heise-atom.xml', 'https://www.heise.de', 'Technologia', 'DE', 'de', 'technologia', 11, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'de-golem', 'Golem.de', 'https://rss.golem.de/rss.php?feed=RSS2.0', 'https://www.golem.de', 'Technologia', 'DE', 'de', 'technologia', 12, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'de-netzpolitik', 'netzpolitik.org', 'https://netzpolitik.org/feed/', 'https://netzpolitik.org', 'Prawa cyfrowe', 'DE', 'de', 'technologia', 13, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'de-kicker', 'kicker', 'https://newsfeed.kicker.de/news/aktuell', 'https://www.kicker.de', 'Sport', 'DE', 'de', 'sport', 14, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'de-bundesbank', 'Deutsche Bundesbank', 'https://www.bundesbank.de/service/rss/de/1234/feed.xml', 'https://www.bundesbank.de', 'Bank centralny', 'DE', 'de', 'biznes', 15, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'at-derstandard', 'Der Standard', 'https://www.derstandard.at/rss', 'https://www.derstandard.at', 'Dziennik, lewa strona centrum', 'AT', 'de', 'wiadomosci', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'at-diepresse', 'Die Presse', 'https://www.diepresse.com/rss/home', 'https://www.diepresse.com', 'Dziennik, prawa strona centrum', 'AT', 'de', 'wiadomosci', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'at-orf', 'ORF News', 'https://rss.orf.at/news.xml', 'https://orf.at', 'Nadawca publiczny', 'AT', 'de', 'wiadomosci', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'ch-nzz', 'Neue Zürcher Zeitung', 'https://www.nzz.ch/recent.rss', 'https://www.nzz.ch', 'Dziennik, liberalny', 'CH', 'de', 'wiadomosci', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'ch-srf', 'SRF News', 'https://www.srf.ch/news/bnf/rss/1646', 'https://www.srf.ch/news', 'Nadawca publiczny', 'CH', 'de', 'wiadomosci', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'ch-swissinfo', 'SWI swissinfo.ch', 'https://www.swissinfo.ch/service/rss/latest/45641510', 'https://www.swissinfo.ch', 'Nadawca zagraniczny', 'CH', 'en', 'wiadomosci', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'fr-lemonde', 'Le Monde', 'https://www.lemonde.fr/rss/une.xml', 'https://www.lemonde.fr', 'Dziennik, lewa strona centrum', 'FR', 'fr', 'wiadomosci', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'fr-lefigaro', 'Le Figaro', 'https://www.lefigaro.fr/rss/figaro_actualites.xml', 'https://www.lefigaro.fr', 'Dziennik, prawa strona', 'FR', 'fr', 'wiadomosci', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'fr-liberation', 'Libération', 'https://www.liberation.fr/arc/outboundfeeds/collection/accueil-une/?outputType=xml', 'https://www.liberation.fr', 'Dziennik, lewa strona', 'FR', 'fr', 'wiadomosci', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'fr-lesechos', 'Les Échos', 'https://services.lesechos.fr/rss/les-echos-economie.xml', 'https://www.lesechos.fr', 'Dziennik gospodarczy', 'FR', 'fr', 'biznes', 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'fr-france24', 'France 24', 'https://www.france24.com/fr/rss', 'https://www.france24.com/fr', 'Nadawca publiczny', 'FR', 'fr', 'wiadomosci', 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'fr-rfi', 'RFI', 'https://www.rfi.fr/fr/rss', 'https://www.rfi.fr', 'Radio zagraniczne', 'FR', 'fr', 'wiadomosci', 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'fr-mediapart', 'Mediapart', 'https://www.mediapart.fr/articles/feed', 'https://www.mediapart.fr', 'Dziennikarstwo śledcze', 'FR', 'fr', 'opinie', 7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'fr-lequipe', 'L''Équipe', 'https://www.lequipe.fr/rss/actu_rss.xml', 'https://www.lequipe.fr', 'Sport', 'FR', 'fr', 'sport', 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'fr-numerama', 'Numerama', 'https://www.numerama.com/feed/', 'https://www.numerama.com', 'Technologia', 'FR', 'fr', 'technologia', 9, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'fr-nextinpact', 'Next', 'https://next.ink/feed/', 'https://next.ink', 'Technologia', 'FR', 'fr', 'technologia', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'be-lesoir', 'Le Soir', 'https://www.lesoir.be/rss/1_1', 'https://www.lesoir.be', 'Dziennik', 'BE', 'fr', 'wiadomosci', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'be-vrt', 'VRT NWS', 'https://www.vrt.be/vrtnws/nl.rss.articles.xml', 'https://www.vrt.be/vrtnws', 'Nadawca publiczny', 'BE', 'nl', 'wiadomosci', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'be-brussels-times', 'The Brussels Times', 'https://www.brusselstimes.com/feed', 'https://www.brusselstimes.com', 'Bruksela po angielsku', 'BE', 'en', 'wiadomosci', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'es-elpais', 'El País', 'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada', 'https://elpais.com', 'Dziennik, lewa strona centrum', 'ES', 'es', 'wiadomosci', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'es-elmundo', 'El Mundo', 'https://e00-elmundo.uecdn.es/elmundo/rss/portada.xml', 'https://www.elmundo.es', 'Dziennik, prawa strona centrum', 'ES', 'es', 'wiadomosci', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'es-abc', 'ABC', 'https://www.abc.es/rss/2.0/portada/', 'https://www.abc.es', 'Dziennik, prawa strona', 'ES', 'es', 'wiadomosci', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'es-lavanguardia', 'La Vanguardia', 'https://www.lavanguardia.com/rss/home.xml', 'https://www.lavanguardia.com', 'Dziennik', 'ES', 'es', 'wiadomosci', 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'es-eldiario', 'elDiario.es', 'https://www.eldiario.es/rss/', 'https://www.eldiario.es', 'Lewa strona', 'ES', 'es', 'wiadomosci', 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'es-marca', 'Marca', 'https://e00-marca.uecdn.es/rss/portada.xml', 'https://www.marca.com', 'Sport', 'ES', 'es', 'sport', 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'es-xataka', 'Xataka', 'https://www.xataka.com/feedburner.xml', 'https://www.xataka.com', 'Technologia', 'ES', 'es', 'technologia', 7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'pt-publico', 'Público', 'https://feeds.feedburner.com/PublicoRSS', 'https://www.publico.pt', 'Dziennik', 'PT', 'pt', 'wiadomosci', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'pt-observador', 'Observador', 'https://observador.pt/feed/', 'https://observador.pt', 'Dziennik', 'PT', 'pt', 'wiadomosci', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'it-corriere', 'Corriere della Sera', 'https://xml2.corriereobjects.it/rss/homepage.xml', 'https://www.corriere.it', 'Dziennik', 'IT', 'it', 'wiadomosci', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'it-repubblica', 'la Repubblica', 'https://www.repubblica.it/rss/homepage/rss2.0.xml', 'https://www.repubblica.it', 'Dziennik, lewa strona centrum', 'IT', 'it', 'wiadomosci', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'it-lastampa', 'La Stampa', 'https://www.lastampa.it/rss/homepage.xml', 'https://www.lastampa.it', 'Dziennik', 'IT', 'it', 'wiadomosci', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'it-ilsole24ore', 'Il Sole 24 Ore', 'https://www.ilsole24ore.com/rss/italia.xml', 'https://www.ilsole24ore.com', 'Dziennik gospodarczy', 'IT', 'it', 'biznes', 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'it-ansa', 'ANSA', 'https://www.ansa.it/sito/ansait_rss.xml', 'https://www.ansa.it', 'Agencja prasowa', 'IT', 'it', 'wiadomosci', 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'it-gazzetta', 'La Gazzetta dello Sport', 'https://www.gazzetta.it/rss/home.xml', 'https://www.gazzetta.it', 'Sport', 'IT', 'it', 'sport', 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'nl-nos', 'NOS Nieuws', 'https://feeds.nos.nl/nosnieuwsalgemeen', 'https://nos.nl', 'Nadawca publiczny', 'NL', 'nl', 'wiadomosci', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'nl-nrc', 'NRC', 'https://www.nrc.nl/rss/', 'https://www.nrc.nl', 'Dziennik', 'NL', 'nl', 'wiadomosci', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("key") DO NOTHING;

-- Wsad 8/9 — kraje: AU, BR, CA, CN, CZ, DK, FI, IL, IN, JP, LT, NL, NO, QA, RU, SE, SK, UA, —
INSERT INTO "NewsSourceCatalog" ("id","key","name","rssUrl","homepageUrl","descriptor","country","language","category","sortOrder","createdAt","updatedAt") VALUES
  (gen_random_uuid()::text, 'nl-volkskrant', 'de Volkskrant', 'https://www.volkskrant.nl/voorpagina/rss.xml', 'https://www.volkskrant.nl', 'Dziennik', 'NL', 'nl', 'wiadomosci', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'nl-dutchnews', 'DutchNews.nl', 'https://www.dutchnews.nl/feed/', 'https://www.dutchnews.nl', 'Holandia po angielsku', 'NL', 'en', 'wiadomosci', 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'nl-tweakers', 'Tweakers', 'https://feeds.feedburner.com/tweakers/mixed', 'https://tweakers.net', 'Technologia', 'NL', 'nl', 'technologia', 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'se-svt', 'SVT Nyheter', 'https://www.svt.se/nyheter/rss.xml', 'https://www.svt.se/nyheter', 'Nadawca publiczny', 'SE', 'sv', 'wiadomosci', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'se-dn', 'Dagens Nyheter', 'https://www.dn.se/rss/', 'https://www.dn.se', 'Dziennik', 'SE', 'sv', 'wiadomosci', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'se-svd', 'Svenska Dagbladet', 'https://www.svd.se/feed/articles.rss', 'https://www.svd.se', 'Dziennik', 'SE', 'sv', 'wiadomosci', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'se-thelocal', 'The Local Sweden', 'https://www.thelocal.se/feeds/rss.php', 'https://www.thelocal.se', 'Szwecja po angielsku', 'SE', 'en', 'wiadomosci', 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'no-nrk', 'NRK Nyheter', 'https://www.nrk.no/toppsaker.rss', 'https://www.nrk.no', 'Nadawca publiczny', 'NO', 'no', 'wiadomosci', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'no-aftenposten', 'Aftenposten', 'https://www.aftenposten.no/rss', 'https://www.aftenposten.no', 'Dziennik', 'NO', 'no', 'wiadomosci', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'dk-dr', 'DR Nyheder', 'https://www.dr.dk/nyheder/service/feeds/allenyheder', 'https://www.dr.dk/nyheder', 'Nadawca publiczny', 'DK', 'da', 'wiadomosci', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'dk-politiken', 'Politiken', 'https://politiken.dk/rss/senestenyt.rss', 'https://politiken.dk', 'Dziennik', 'DK', 'da', 'wiadomosci', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'fi-yle', 'Yle Uutiset', 'https://feeds.yle.fi/uutiset/v1/majorHeadlines/YLE_UUTISET.rss', 'https://yle.fi/uutiset', 'Nadawca publiczny', 'FI', 'fi', 'wiadomosci', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'fi-yle-news', 'Yle News', 'https://feeds.yle.fi/uutiset/v1/majorHeadlines/YLE_NEWS.rss', 'https://yle.fi/news', 'Finlandia po angielsku', 'FI', 'en', 'wiadomosci', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'fi-helsinki-times', 'Helsinki Times', 'https://www.helsinkitimes.fi/?format=feed&type=rss', 'https://www.helsinkitimes.fi', 'Finlandia po angielsku', 'FI', 'en', 'wiadomosci', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'cz-irozhlas', 'iROZHLAS', 'https://www.irozhlas.cz/rss/irozhlas', 'https://www.irozhlas.cz', 'Radio publiczne', 'CZ', 'cs', 'wiadomosci', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'cz-ct24', 'ČT24', 'https://ct24.ceskatelevize.cz/rss/hlavni-zpravy', 'https://ct24.ceskatelevize.cz', 'Telewizja publiczna', 'CZ', 'cs', 'wiadomosci', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'cz-idnes', 'iDNES.cz', 'https://servis.idnes.cz/rss.aspx?c=zpravodaj', 'https://www.idnes.cz', 'Dziennik', 'CZ', 'cs', 'wiadomosci', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'cz-denikn', 'Deník N', 'https://denikn.cz/feed/', 'https://denikn.cz', 'Dziennik', 'CZ', 'cs', 'wiadomosci', 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'cz-expats', 'Expats.cz', 'https://www.expats.cz/rss', 'https://www.expats.cz', 'Czechy po angielsku', 'CZ', 'en', 'wiadomosci', 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'sk-dennikn', 'Denník N', 'https://dennikn.sk/feed/', 'https://dennikn.sk', 'Dziennik', 'SK', 'sk', 'wiadomosci', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'sk-sme', 'SME.sk', 'https://www.sme.sk/rss-title', 'https://www.sme.sk', 'Dziennik', 'SK', 'sk', 'wiadomosci', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'ua-pravda', 'Українська правда', 'https://www.pravda.com.ua/rss/', 'https://www.pravda.com.ua', 'Dziennik', 'UA', 'uk', 'wiadomosci', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'ua-kyiv-independent', 'The Kyiv Independent', 'https://kyivindependent.com/feed/', 'https://kyivindependent.com', 'Ukraina po angielsku', 'UA', 'en', 'wiadomosci', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'ua-kyiv-post', 'Kyiv Post', 'https://www.kyivpost.com/feed', 'https://www.kyivpost.com', 'Ukraina po angielsku', 'UA', 'en', 'wiadomosci', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'ua-suspilne', 'Суспільне Новини', 'https://suspilne.media/rss/all.rss', 'https://suspilne.media', 'Nadawca publiczny', 'UA', 'uk', 'wiadomosci', 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'lt-lrt', 'LRT', 'https://www.lrt.lt/naujienos/rss', 'https://www.lrt.lt', 'Nadawca publiczny', 'LT', 'lt', 'wiadomosci', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'lt-lrt-en', 'LRT English', 'https://www.lrt.lt/en/news-in-english/rss', 'https://www.lrt.lt/en', 'Litwa po angielsku', 'LT', 'en', 'wiadomosci', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'ru-meduza-en', 'Meduza — English', 'https://meduza.io/rss/en/all', 'https://meduza.io/en', 'Niezależny, na emigracji', 'RU', 'en', 'wiadomosci', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'ru-novaya-europe', 'Novaya Gazeta Europe', 'https://novayagazeta.eu/feed/rss', 'https://novayagazeta.eu', 'Niezależny, na emigracji', 'RU', 'ru', 'wiadomosci', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'ru-moscow-times-en', 'The Moscow Times — English', 'https://www.themoscowtimes.com/rss/news', 'https://www.themoscowtimes.com', 'Niezależny, na emigracji', 'RU', 'en', 'wiadomosci', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'ca-cbc-top', 'CBC News — Top Stories', 'https://www.cbc.ca/webfeed/rss/rss-topstories', 'https://www.cbc.ca/news', 'Nadawca publiczny', 'CA', 'en', 'wiadomosci', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'ca-globe-and-mail', 'The Globe and Mail', 'https://www.theglobeandmail.com/arc/outboundfeeds/rss/category/canada/', 'https://www.theglobeandmail.com', 'Dziennik', 'CA', 'en', 'wiadomosci', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'ca-national-post', 'National Post', 'https://nationalpost.com/feed/', 'https://nationalpost.com', 'Dziennik, prawa strona', 'CA', 'en', 'wiadomosci', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'au-abc-news', 'ABC News Australia', 'https://www.abc.net.au/news/feed/2942460/rss.xml', 'https://www.abc.net.au/news', 'Nadawca publiczny', 'AU', 'en', 'wiadomosci', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'au-smh', 'The Sydney Morning Herald', 'https://www.smh.com.au/rss/feed.xml', 'https://www.smh.com.au', 'Dziennik', 'AU', 'en', 'wiadomosci', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'au-the-conversation', 'The Conversation AU', 'https://theconversation.com/au/articles.atom', 'https://theconversation.com/au', 'Akademicki', 'AU', 'en', 'nauka', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'jp-japan-times', 'The Japan Times', 'https://www.japantimes.co.jp/feed/', 'https://www.japantimes.co.jp', 'Japonia po angielsku', 'JP', 'en', 'wiadomosci', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'jp-nhk-world', 'NHK World-Japan', 'https://www3.nhk.or.jp/nhkworld/en/news/feeds/', 'https://www3.nhk.or.jp/nhkworld', 'Nadawca publiczny', 'JP', 'en', 'wiadomosci', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'jp-nikkei-asia', 'Nikkei Asia', 'https://asia.nikkei.com/rss/feed/nar', 'https://asia.nikkei.com', 'Gospodarka Azji', 'JP', 'en', 'biznes', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'in-the-hindu', 'The Hindu', 'https://www.thehindu.com/news/national/feeder/default.rss', 'https://www.thehindu.com', 'Dziennik', 'IN', 'en', 'wiadomosci', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'in-indian-express', 'The Indian Express', 'https://indianexpress.com/feed/', 'https://indianexpress.com', 'Dziennik', 'IN', 'en', 'wiadomosci', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'in-scroll', 'Scroll.in', 'https://scroll.in/feed', 'https://scroll.in', 'Serwis informacyjny', 'IN', 'en', 'wiadomosci', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'br-folha', 'Folha de S.Paulo', 'https://feeds.folha.uol.com.br/emcimadahora/rss091.xml', 'https://www.folha.uol.com.br', 'Dziennik', 'BR', 'pt', 'wiadomosci', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'br-g1', 'G1', 'https://g1.globo.com/rss/g1/', 'https://g1.globo.com', 'Serwis informacyjny', 'BR', 'pt', 'wiadomosci', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'il-haaretz', 'Haaretz — English', 'https://www.haaretz.com/srv/haaretz-latest.xml', 'https://www.haaretz.com', 'Dziennik, lewa strona', 'IL', 'en', 'wiadomosci', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'il-times-of-israel', 'The Times of Israel', 'https://www.timesofisrael.com/feed/', 'https://www.timesofisrael.com', 'Dziennik', 'IL', 'en', 'wiadomosci', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'qa-al-jazeera', 'Al Jazeera — English', 'https://www.aljazeera.com/xml/rss/all.xml', 'https://www.aljazeera.com', 'Telewizja informacyjna', 'QA', 'en', 'wiadomosci', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'cn-scmp', 'South China Morning Post', 'https://www.scmp.com/rss/91/feed', 'https://www.scmp.com', 'Hongkong po angielsku', 'CN', 'en', 'wiadomosci', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'cn-caixin', 'Caixin Global', 'https://www.caixinglobal.com/feed/', 'https://www.caixinglobal.com', 'Gospodarka Chin', 'CN', 'en', 'biznes', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-cyclingnews', 'Cyclingnews', 'https://www.cyclingnews.com/rss/news/', 'https://www.cyclingnews.com', 'Kolarstwo', '', 'en', 'sport', 64, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("key") DO NOTHING;

-- Wsad 9/9 — kraje: PL, —
INSERT INTO "NewsSourceCatalog" ("id","key","name","rssUrl","homepageUrl","descriptor","country","language","category","sortOrder","createdAt","updatedAt") VALUES
  (gen_random_uuid()::text, 'intl-bikeradar', 'BikeRadar', 'https://www.bikeradar.com/feed', 'https://www.bikeradar.com', 'Rowery', '', 'en', 'sport', 65, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-motor1', 'Motor1', 'https://www.motor1.com/rss/news/all/', 'https://www.motor1.com', 'Motoryzacja', '', 'en', 'inne', 66, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-electrek', 'Electrek', 'https://electrek.co/feed/', 'https://electrek.co', 'Elektromobilność', '', 'en', 'technologia', 67, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-insideevs', 'InsideEVs', 'https://insideevs.com/rss/news/all/', 'https://insideevs.com', 'Elektromobilność', '', 'en', 'technologia', 68, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'pl-autokult', 'Autokult', 'https://autokult.pl/feed', 'https://autokult.pl', 'Motoryzacja', 'PL', 'pl', 'inne', 133, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'pl-auto-swiat', 'Auto Świat', 'https://www.auto-swiat.pl/.feed', 'https://www.auto-swiat.pl', 'Motoryzacja', 'PL', 'pl', 'inne', 134, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'pl-elektrowoz', 'Elektrowoz', 'https://elektrowoz.pl/feed/', 'https://elektrowoz.pl', 'Elektromobilność', 'PL', 'pl', 'technologia', 135, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'pl-muratordom', 'Murator', 'https://muratordom.pl/rss.xml', 'https://muratordom.pl', 'Budowa i remont', 'PL', 'pl', 'inne', 136, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'pl-ogrodinfo', 'Ogrodinfo', 'https://www.ogrodinfo.pl/feed/', 'https://www.ogrodinfo.pl', 'Ogrodnictwo', 'PL', 'pl', 'inne', 137, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'pl-podroze-national', 'Podróże', 'https://www.national-geographic.pl/traveler/feed', 'https://www.national-geographic.pl/traveler', 'Podróże', 'PL', 'pl', 'inne', 138, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-atlas-obscura', 'Atlas Obscura', 'https://www.atlasobscura.com/feeds/latest', 'https://www.atlasobscura.com', 'Podróże i ciekawostki', '', 'en', 'inne', 69, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'pl-fotoblogia', 'Fotoblogia', 'https://fotoblogia.pl/feed', 'https://fotoblogia.pl', 'Fotografia', 'PL', 'pl', 'kultura', 139, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-petapixel', 'PetaPixel', 'https://petapixel.com/feed/', 'https://petapixel.com', 'Fotografia', '', 'en', 'kultura', 70, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-dpreview', 'DPReview', 'https://www.dpreview.com/feeds/news.xml', 'https://www.dpreview.com', 'Fotografia', '', 'en', 'technologia', 71, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'pl-zwierzeta-swiat', 'Świat Zwierząt', 'https://www.swiatzwierzat.pl/feed/', 'https://www.swiatzwierzat.pl', 'Zwierzęta', 'PL', 'pl', 'inne', 140, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-terrarium-reptiles', 'Reptiles Magazine', 'https://reptilesmagazine.com/feed/', 'https://reptilesmagazine.com', 'Terrarystyka', '', 'en', 'inne', 72, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'pl-kuchnia-kwestia-smaku', 'Kwestia Smaku', 'https://www.kwestiasmaku.com/rss.xml', 'https://www.kwestiasmaku.com', 'Kuchnia', 'PL', 'pl', 'inne', 141, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'pl-jadlonomia', 'Jadłonomia', 'https://www.jadlonomia.com/feed/', 'https://www.jadlonomia.com', 'Kuchnia roślinna', 'PL', 'pl', 'inne', 142, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'intl-food52', 'Food52', 'https://food52.com/blog.rss', 'https://food52.com', 'Kuchnia', '', 'en', 'inne', 73, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("key") DO NOTHING;
