export const EMOJI_DATA: { emoji: string; keywords: string[] }[] = [
  // Warzywa i owoce
  { emoji: "🥕", keywords: ["marchew","carrot","warzywo","produce","vegetable"] },
  { emoji: "🍎", keywords: ["jabłko","apple","owoc","fruit","czerwony"] },
  { emoji: "🍊", keywords: ["pomarańcza","orange","cytrus","citrus"] },
  { emoji: "🍋", keywords: ["cytryna","lemon","limonka","cytrus"] },
  { emoji: "🍇", keywords: ["winogrona","grape","winogron","fruit"] },
  { emoji: "🍓", keywords: ["truskawka","strawberry","owoc","berry"] },
  { emoji: "🫐", keywords: ["borówka","blueberry","jagoda","berry"] },
  { emoji: "🍒", keywords: ["czereśnia","wisnia","cherry","owoc"] },
  { emoji: "🍑", keywords: ["brzoskwinia","peach","owoc","fruit"] },
  { emoji: "🥭", keywords: ["mango","fruit","owoc","tropikalny"] },
  { emoji: "🍍", keywords: ["ananas","pineapple","tropikalny"] },
  { emoji: "🥝", keywords: ["kiwi","fruit","owoc","zielony"] },
  { emoji: "🍅", keywords: ["pomidor","tomato","warzywo","czerwony"] },
  { emoji: "🫑", keywords: ["papryka","pepper","bell pepper","warzywo"] },
  { emoji: "🥦", keywords: ["brokuł","broccoli","warzywo","zielony"] },
  { emoji: "🥬", keywords: ["sałata","lettuce","liściowe","warzywo"] },
  { emoji: "🥒", keywords: ["ogórek","cucumber","warzywo","zielony"] },
  { emoji: "🌽", keywords: ["kukurydza","corn","warzywo","żółty"] },
  { emoji: "🥑", keywords: ["awokado","avocado","owoc","zielony"] },
  { emoji: "🧅", keywords: ["cebula","onion","warzywo"] },
  { emoji: "🧄", keywords: ["czosnek","garlic","warzywo","przyprawa"] },
  { emoji: "🥔", keywords: ["ziemniak","potato","warzywo","skrobia"] },
  { emoji: "🍠", keywords: ["bataty","sweet potato","warzywo"] },
  { emoji: "🌶️", keywords: ["chili","pepper","ostra","spicy","przyprawa"] },
  { emoji: "🫘", keywords: ["fasola","bean","groch","rośliny strączkowe"] },
  { emoji: "🥜", keywords: ["orzeszki","peanut","orzech","nut"] },
  { emoji: "🌰", keywords: ["kasztan","chestnut","orzech","nut"] },
  { emoji: "🍄", keywords: ["grzyb","mushroom","warzywo","las"] },
  { emoji: "🫚", keywords: ["oliwa","olive oil","olej","tłuszcz","condiment"] },
  // Pieczywo i zboża
  { emoji: "🍞", keywords: ["chleb","bread","pieczywo","bakery","pszenny"] },
  { emoji: "🥖", keywords: ["bagietka","baguette","pieczywo","french"] },
  { emoji: "🥐", keywords: ["rogalik","croissant","pieczywo","masło"] },
  { emoji: "🧁", keywords: ["babeczka","cupcake","ciasto","słodycze","sweet"] },
  { emoji: "🎂", keywords: ["tort","cake","ciasto","urodziny","birthday"] },
  { emoji: "🍰", keywords: ["ciasto","cake","deser","sweet","słodki"] },
  { emoji: "🥧", keywords: ["ciasto","pie","tarta","deser"] },
  { emoji: "🍩", keywords: ["donut","pączek","słodycze","sweet"] },
  { emoji: "🍪", keywords: ["ciastko","cookie","herbatnik","słodycze"] },
  { emoji: "🥨", keywords: ["precel","pretzel","przekąska","snack"] },
  { emoji: "🥞", keywords: ["naleśnik","pancake","śniadanie","breakfast"] },
  { emoji: "🧇", keywords: ["gofr","waffle","śniadanie","breakfast"] },
  // Nabiał i jajka
  { emoji: "🧀", keywords: ["ser","cheese","nabiał","dairy","żółty"] },
  { emoji: "🥛", keywords: ["mleko","milk","nabiał","dairy","biały"] },
  { emoji: "🫙", keywords: ["słoik","jar","jogurt","śmietana","kondyment","condiment"] },
  { emoji: "🧈", keywords: ["masło","butter","nabiał","dairy"] },
  { emoji: "🥚", keywords: ["jajko","egg","nabiał","śniadanie","breakfast"] },
  { emoji: "🍳", keywords: ["jajko","egg","smażone","fried","patelnia"] },
  // Mięso i ryby
  { emoji: "🥩", keywords: ["mięso","meat","beef","wołowina","steak"] },
  { emoji: "🍗", keywords: ["kurczak","chicken","drób","poultry","noga"] },
  { emoji: "🍖", keywords: ["żeberka","ribs","mięso","meat","kość"] },
  { emoji: "🥓", keywords: ["boczek","bacon","wieprzowina","pork","wędlina"] },
  { emoji: "🌭", keywords: ["hot dog","parówka","kiełbasa","sausage","wurst"] },
  { emoji: "🍔", keywords: ["burger","hamburguer","mięso","fast food"] },
  { emoji: "🐟", keywords: ["ryba","fish","łosoś","owoce morza","seafood"] },
  { emoji: "🦐", keywords: ["krewetki","shrimp","prawns","owoce morza","seafood"] },
  { emoji: "🦑", keywords: ["kałamarnica","squid","owoce morza","seafood"] },
  { emoji: "🦀", keywords: ["krab","crab","owoce morza","seafood"] },
  { emoji: "🦞", keywords: ["homar","lobster","owoce morza","seafood"] },
  { emoji: "🐠", keywords: ["ryba","fish","tropikalna","owoce morza"] },
  // Napoje
  { emoji: "🍺", keywords: ["piwo","beer","alkohol","drinks","napój"] },
  { emoji: "🍻", keywords: ["piwo","beer","toast","napój","drinks"] },
  { emoji: "🍷", keywords: ["wino","wine","czerwone","alkohol","drinks"] },
  { emoji: "🥂", keywords: ["szampan","champagne","prosecco","alkohol"] },
  { emoji: "🍸", keywords: ["koktajl","cocktail","drink","alkohol"] },
  { emoji: "🍹", keywords: ["koktajl","tropical drink","sok","juice"] },
  { emoji: "🧉", keywords: ["maté","yerba","herbata","drink","napój"] },
  { emoji: "🥤", keywords: ["sok","juice","cola","napój","drink","smoothie"] },
  { emoji: "🧋", keywords: ["bubble tea","herbata","mleczna","drink"] },
  { emoji: "☕", keywords: ["kawa","coffee","espresso","cappuccino","napój"] },
  { emoji: "🫖", keywords: ["herbata","tea","czajnik","napój"] },
  { emoji: "🧃", keywords: ["sok","juice","karton","dziecięcy","napój"] },
  { emoji: "💧", keywords: ["woda","water","mineralna","napój","hydratacja"] },
  { emoji: "🍵", keywords: ["herbata","tea","matcha","zielona","napój"] },
  // Przekąski i słodycze
  { emoji: "🍫", keywords: ["czekolada","chocolate","słodycze","sweet","kakao"] },
  { emoji: "🍬", keywords: ["cukierek","candy","słodycze","sweet","cukier"] },
  { emoji: "🍭", keywords: ["lizak","lollipop","cukierek","słodycze"] },
  { emoji: "🍮", keywords: ["budyń","pudding","deser","dessert","słodki"] },
  { emoji: "🍯", keywords: ["miód","honey","naturalny","słodki","pszczoła"] },
  { emoji: "🍿", keywords: ["popcorn","przekąska","snack","kinowy","corn"] },
  { emoji: "🧆", keywords: ["falafel","ciecierzyca","przekąska","snack"] },
  { emoji: "🧂", keywords: ["sól","salt","przyprawa","spice","solony"] },
  { emoji: "🍡", keywords: ["mochi","dango","słodycze","azjatyckie","snack"] },
  { emoji: "🍢", keywords: ["oden","japońskie","przekąska","snack"] },
  // Dania i fast food
  { emoji: "🍕", keywords: ["pizza","włoska","fast food","ser","pomidor"] },
  { emoji: "🌮", keywords: ["taco","meksykańskie","fast food","tortilla"] },
  { emoji: "🌯", keywords: ["wrap","tortilla","kanapka","sandwich"] },
  { emoji: "🥙", keywords: ["gyros","wrap","kebab","mięso","fast food"] },
  { emoji: "🥗", keywords: ["sałatka","salad","zdrowe","healthy","warzywa"] },
  { emoji: "🍲", keywords: ["zupa","stew","gulasz","garnek","obiad"] },
  { emoji: "🫕", keywords: ["fondue","garnek","obiad","gotowane"] },
  { emoji: "🥘", keywords: ["paella","gulasz","ryż","obiad","danie"] },
  { emoji: "🍜", keywords: ["ramen","makaron","zupa","azjatyckie","noodle"] },
  { emoji: "🍝", keywords: ["spaghetti","pasta","makaron","włoskie","bolognese"] },
  { emoji: "🍛", keywords: ["curry","ryż","indyjskie","ostre","obiad"] },
  { emoji: "🍣", keywords: ["sushi","ryba","japoński","ryż","owoce morza"] },
  { emoji: "🍱", keywords: ["bento","lunch box","japoński","obiad","pudełko"] },
  { emoji: "🥫", keywords: ["konserwa","puszka","can","preserved","warzywa"] },
  // Przyprawy i zioła
  { emoji: "🌿", keywords: ["zioła","herbs","świeże","basil","bazylia","pietruszka"] },
  { emoji: "🫛", keywords: ["groszek","pea","strączek","zielony","warzywo"] },
  // Chemia i higiena
  { emoji: "🧴", keywords: ["szampon","płyn","kosmetyk","hygiene","cleaning","krem"] },
  { emoji: "🧼", keywords: ["mydło","soap","hygiene","czystość","cleaning"] },
  { emoji: "🪥", keywords: ["szczoteczka","toothbrush","zęby","hygiene","dental"] },
  { emoji: "🧻", keywords: ["papier toaletowy","toilet paper","chusteczki","hygiene"] },
  { emoji: "🪒", keywords: ["maszynka","razor","golenie","shave","hygiene"] },
  { emoji: "💊", keywords: ["lek","medicine","tabletka","pill","zdrowie","health"] },
  { emoji: "🩺", keywords: ["lekarz","doctor","zdrowie","health","medycyna"] },
  { emoji: "🩹", keywords: ["plaster","bandage","apteczka","first aid","zdrowie"] },
  { emoji: "🧪", keywords: ["laboratorium","chemistry","test","zdrowie","supplement"] },
  { emoji: "🪣", keywords: ["wiadro","bucket","cleaning","sprzątanie"] },
  { emoji: "🧹", keywords: ["miotła","broom","sprzątanie","cleaning","sweep"] },
  { emoji: "🧺", keywords: ["kosz","basket","pranie","laundry","cleaning"] },
  { emoji: "🫧", keywords: ["bąbelki","bubbles","płyn","cleaning","mycie"] },
  // Dom i kuchnia
  { emoji: "🏠", keywords: ["dom","house","home","mieszkanie","budynek"] },
  { emoji: "🛒", keywords: ["koszyk","shopping cart","zakupy","sklep","store"] },
  { emoji: "🍽️", keywords: ["talerz","plate","obiad","danie","naczynia"] },
  { emoji: "🥄", keywords: ["łyżka","spoon","sztućce","kuchnia","gotowanie"] },
  { emoji: "🍴", keywords: ["sztućce","cutlery","widelec","nóż","fork"] },
  { emoji: "🔪", keywords: ["nóż","knife","kuchenny","kuchnia","gotowanie"] },
  { emoji: "🧊", keywords: ["lód","ice","mrożone","frozen","zimne","kostka"] },
  { emoji: "🪴", keywords: ["roślina","plant","doniczkowa","kwiat","ogród"] },
  { emoji: "🌱", keywords: ["sadzonka","seedling","roślina","kiełkować","ogród"] },
  { emoji: "🌷", keywords: ["tulipan","tulip","kwiat","flower","ogród","prezent"] },
  { emoji: "🌸", keywords: ["kwiat","blossom","cherry","wiosna","spring"] },
  { emoji: "💐", keywords: ["bukiet","bouquet","kwiaty","flowers","prezent"] },
  // Transport i motoryzacja
  { emoji: "🚗", keywords: ["auto","car","samochód","transport","jeżdżenie"] },
  { emoji: "⛽", keywords: ["benzyna","fuel","paliwo","stacja","gas"] },
  { emoji: "🛞", keywords: ["opona","tire","tyre","koło","auto","samochód"] },
  { emoji: "🔧", keywords: ["klucz","wrench","naprawa","repair","narzędzie"] },
  { emoji: "🚲", keywords: ["rower","bike","bicycle","transport","sport"] },
  { emoji: "🛵", keywords: ["skuter","scooter","motor","transport"] },
  { emoji: "✈️", keywords: ["samolot","airplane","podróż","travel","lot"] },
  // Sport i aktywność
  { emoji: "⚽", keywords: ["piłka","football","soccer","sport","kopanie"] },
  { emoji: "🏋️", keywords: ["siłownia","gym","sport","trening","fitness"] },
  { emoji: "🏃", keywords: ["bieganie","running","sport","jogging","trening"] },
  { emoji: "🧘", keywords: ["joga","yoga","medytacja","relaks","sport"] },
  { emoji: "🎾", keywords: ["tenis","tennis","sport","rakieta","piłka"] },
  { emoji: "🏊", keywords: ["pływanie","swimming","sport","basen","woda"] },
  // Elektronika i narzędzia
  { emoji: "💡", keywords: ["żarówka","bulb","light","elektryczny","dom"] },
  { emoji: "🔋", keywords: ["bateria","battery","elektryczny","ładowanie"] },
  { emoji: "🖨️", keywords: ["drukarka","printer","atrament","tusz","biuro"] },
  { emoji: "📱", keywords: ["telefon","phone","mobile","smartfon","elektronika"] },
  { emoji: "💻", keywords: ["laptop","komputer","elektronika","praca","computer"] },
  { emoji: "🖥️", keywords: ["monitor","komputer","elektronika","desktop"] },
  { emoji: "🎮", keywords: ["gry","games","konsola","rozrywka","controller"] },
  { emoji: "📸", keywords: ["aparat","camera","zdjęcia","foto","photography"] },
  // Dzieci i zabawki
  { emoji: "🧸", keywords: ["miś","teddy","zabawka","toy","dziecko","baby"] },
  { emoji: "🍼", keywords: ["butelka","bottle","dziecko","baby","niemowlę"] },
  { emoji: "🧷", keywords: ["agrafka","pin","dziecko","baby","pieluszka","diaper"] },
  { emoji: "🪀", keywords: ["jojo","yoyo","zabawka","toy","dziecko"] },
  { emoji: "🎈", keywords: ["balon","balloon","urodziny","birthday","impreza"] },
  // Biuro i szkoła
  { emoji: "📚", keywords: ["książki","books","nauka","szkoła","education"] },
  { emoji: "✏️", keywords: ["ołówek","pencil","pisanie","szkoła","writing"] },
  { emoji: "📝", keywords: ["notatka","notes","lista","writing","memo"] },
  { emoji: "📦", keywords: ["pudełko","box","opakowanie","package","przesyłka"] },
  { emoji: "🗂️", keywords: ["teczka","folder","dokumenty","biuro","office"] },
  // Zwierzęta i karma
  { emoji: "🐾", keywords: ["łapy","paws","zwierzęta","pets","karma"] },
  { emoji: "🐶", keywords: ["pies","dog","zwierzę","pet","szczeniak"] },
  { emoji: "🐱", keywords: ["kot","cat","zwierzę","pet","kociak"] },
  { emoji: "🐰", keywords: ["królik","rabbit","bunny","zwierzę","pet"] },
  { emoji: "🦜", keywords: ["papuga","parrot","ptak","zwierzę","pet"] },
  { emoji: "🦮", keywords: ["pies","guide dog","zwierzę","pet","karma"] },
  // Prezenty i okazje
  { emoji: "🎁", keywords: ["prezent","gift","opakowanie","urodziny","birthday"] },
  { emoji: "🎀", keywords: ["wstążka","ribbon","dekoracja","prezent","gift"] },
  { emoji: "🎉", keywords: ["impreza","party","konfetti","świętowanie","celebration"] },
  { emoji: "🎊", keywords: ["impreza","party","konfetti","sylwester","celebration"] },
  // Inne przydatne
  { emoji: "⚡", keywords: ["energia","energy","elektryczność","szybko","prąd"] },
  { emoji: "🔑", keywords: ["klucz","key","zamek","bezpieczeństwo","security"] },
  { emoji: "🪑", keywords: ["krzesło","chair","meble","furniture","dom"] },
  { emoji: "🛋️", keywords: ["sofa","couch","meble","furniture","salon"] },
  { emoji: "🛏️", keywords: ["łóżko","bed","sypialnia","bedroom","meble"] },
  { emoji: "🚿", keywords: ["prysznic","shower","łazienka","bathroom","kąpiel"] },
  { emoji: "🛁", keywords: ["wanna","bath","łazienka","bathroom","kąpiel"] },
  { emoji: "🪞", keywords: ["lustro","mirror","łazienka","bathroom","odbicie"] },
  { emoji: "🌍", keywords: ["globus","globe","świat","world","ekologia"] },
  { emoji: "♻️", keywords: ["recykling","recycling","ekologia","green","środowisko"] },
  { emoji: "🛍️", keywords: ["torba","bag","zakupy","shopping","sklep"] },
  { emoji: "💳", keywords: ["karta","card","płatność","bank","finance"] },
  { emoji: "💰", keywords: ["pieniądze","money","kasa","cash","finanse"] },
  { emoji: "🎯", keywords: ["cel","target","dążenie","sport","precise"] },
  { emoji: "🔨", keywords: ["młotek","hammer","narzędzie","tool","naprawa"] },
  { emoji: "🪚", keywords: ["piła","saw","narzędzie","tool","drewno"] },
  { emoji: "⚙️", keywords: ["koło zębate","gear","ustawienia","settings","mechanika"] },
  { emoji: "🧲", keywords: ["magnes","magnet","metalowy","przyciąganie","tool"] },
  { emoji: "🪜", keywords: ["drabina","ladder","narzędzie","tool","dom"] },
  { emoji: "🌡️", keywords: ["termometr","thermometer","temperatura","pogoda","zdrowie"] },
  { emoji: "🌤️", keywords: ["słońce","sun","pogoda","weather","letni"] },
  { emoji: "❄️", keywords: ["śnieg","snow","zimno","cold","zima","winter"] },
  { emoji: "🌧️", keywords: ["deszcz","rain","pogoda","weather","jesień"] },
  { emoji: "🎵", keywords: ["muzyka","music","dźwięk","sound","piosenka"] },
  { emoji: "📺", keywords: ["telewizor","tv","elektronika","rozrywka","ogladanie"] },
];

/** Returns emoji relevant to a given category name (first ~12 items). */
export function getCategoryEmojis(category: string): string[] {
  const lc = category.toLowerCase();
  const keywords = lc.split(/[\s&/]+/);
  const scored = EMOJI_DATA.map((e) => {
    const score = e.keywords.filter((k) =>
      keywords.some((kw) => k.includes(kw) || kw.includes(k))
    ).length;
    return { emoji: e.emoji, score };
  });
  const relevant = scored.filter((e) => e.score > 0).sort((a, b) => b.score - a.score);
  if (relevant.length >= 8) return relevant.slice(0, 12).map((e) => e.emoji);
  // fallback: some generic ones
  return ["📦", "🛒", "🏠", "🎁", "⚙️", "🔑", "🌍"];
}
