// Bakes the audit "book" (content/audyt/manifest.json + per-chapter Markdown
// files) into a generated TypeScript module so the admin panel can render it —
// without shipping it as report migrations and without relying on filesystem
// access in the deployed Next.js server.
//
// Source of truth for STRUCTURE is content/audyt/manifest.json; source of truth
// for CONTENT is content/audyt/<slug>.md. A chapter's status is DERIVED from the
// file: present & non-trivial → "done" (or "draft" if manifest marks it draft),
// absent/near-empty → "planned" (reader shows a "w przygotowaniu" placeholder).
//
// Run as an early step of `npm run build` (see package.json). The generated
// module is committed so `npm run dev` works on a fresh clone; the build just
// refreshes it with whatever is currently on disk.
const fs = require("fs")
const path = require("path")

const ROOT = path.resolve(__dirname, "..")
const CONTENT_DIR = path.join(ROOT, "content", "audyt")
const MANIFEST_PATH = path.join(CONTENT_DIR, "manifest.json")

function readManifest() {
  const raw = fs.readFileSync(MANIFEST_PATH, "utf8")
  return JSON.parse(raw)
}

function readChapter(slug) {
  const abs = path.join(CONTENT_DIR, `${slug}.md`)
  try {
    const content = fs.readFileSync(abs, "utf8")
    const stat = fs.statSync(abs)
    return { content, mtime: stat.mtime.toISOString() }
  } catch {
    return null
  }
}

const manifest = readManifest()

const chapters = manifest.chapters.map((c) => {
  const found = readChapter(c.slug)
  const markdown = found ? found.content : ""
  // "non-trivial" = more than a stub line, so an accidental empty file still
  // shows as planned rather than a blank "done" chapter.
  const hasContent = markdown.trim().length > 40
  const status = hasContent ? (c.draft ? "draft" : "done") : "planned"
  return {
    slug: c.slug,
    number: c.number ?? "",
    part: c.part ?? "",
    title: c.title,
    summary: c.summary ?? "",
    status,
    markdown,
    words: markdown.trim() ? markdown.trim().split(/\s+/).length : 0,
    updatedAt: found ? found.mtime : null,
  }
})

const banner = `// AUTO-GENERATED by scripts/copy-audyt.js — DO NOT EDIT BY HAND.
// Regenerated on every \`npm run build\`. Holds the audit "book" (content/audyt/*)
// for the admin reader at /admin/audyt. Edit content/audyt/*.md instead.
`

const meta = {
  title: manifest.title ?? "Audyt",
  subtitle: manifest.subtitle ?? "",
  auditDate: manifest.auditDate ?? "",
}

const body =
  banner +
  `export interface AudytChapter {\n` +
  `  slug: string\n` +
  `  number: string\n` +
  `  part: string\n` +
  `  title: string\n` +
  `  summary: string\n` +
  `  status: "done" | "draft" | "planned"\n` +
  `  markdown: string\n` +
  `  words: number\n` +
  `  updatedAt: string | null\n` +
  `}\n\n` +
  `export const AUDYT_META = ${JSON.stringify(meta, null, 2)}\n\n` +
  `export const AUDYT_CHAPTERS: AudytChapter[] = ${JSON.stringify(chapters, null, 2)}\n\n` +
  `export const AUDYT_GENERATED_AT = ${JSON.stringify(new Date().toISOString())}\n`

const outDir = path.join(ROOT, "src", "generated")
fs.mkdirSync(outDir, { recursive: true })
const outFile = path.join(outDir, "audyt-book.ts")
fs.writeFileSync(outFile, body, "utf8")

const done = chapters.filter((c) => c.status === "done").length
const draft = chapters.filter((c) => c.status === "draft").length
const planned = chapters.filter((c) => c.status === "planned").length
console.log(
  `✓ copy-audyt: ${chapters.length} rozdziałów (done ${done}, draft ${draft}, planned ${planned}) → src/generated/audyt-book.ts`
)
