// Bakes the repo-root documentation files (CLAUDE.md, doświadczenia.md) into a
// generated TypeScript module so the admin panel can display their *latest*
// version at runtime — without shipping them as report migrations and without
// relying on filesystem access in the deployed (standalone) Next.js server.
//
// Run as the first step of `npm run build` (see package.json). The generated
// module is also committed so `npm run dev` works on a fresh clone; the build
// simply refreshes it with whatever is currently on disk.
const fs = require("fs")
const path = require("path")

// Candidate locations for each doc, in priority order. We run from worldofmag/,
// so the repo root is one level up.
const DOCS = [
  {
    key: "claude",
    title: "CLAUDE.md",
    description: "Instrukcje projektu dla Claude Code (architektura, konwencje, zasady).",
    candidates: ["../CLAUDE.md", "./CLAUDE.md"],
  },
  {
    key: "doswiadczenia",
    title: "doświadczenia.md",
    description: "Lessons learned — dziennik napotkanych problemów i wyciągniętych wniosków.",
    candidates: ["../doświadczenia.md", "./doświadczenia.md"],
  },
]

function readFirst(candidates) {
  for (const rel of candidates) {
    const abs = path.resolve(__dirname, "..", rel)
    try {
      const content = fs.readFileSync(abs, "utf8")
      const stat = fs.statSync(abs)
      return { content, mtime: stat.mtime.toISOString() }
    } catch {
      // try next candidate
    }
  }
  return null
}

const docs = DOCS.map((d) => {
  const found = readFirst(d.candidates)
  const content = found ? found.content : `# ${d.title}\n\n_Plik nie został znaleziony podczas builda._`
  return {
    key: d.key,
    title: d.title,
    description: d.description,
    content,
    lines: content.split("\n").length,
    bytes: Buffer.byteLength(content, "utf8"),
    updatedAt: found ? found.mtime : null,
    found: !!found,
  }
})

const banner = `// AUTO-GENERATED by scripts/copy-docs.js — DO NOT EDIT BY HAND.
// Regenerated on every \`npm run build\`. Holds the latest snapshot of the
// repo-root documentation files for the admin docs viewer.
`

const body =
  banner +
  `export interface AdminDoc {\n` +
  `  key: string\n` +
  `  title: string\n` +
  `  description: string\n` +
  `  content: string\n` +
  `  lines: number\n` +
  `  bytes: number\n` +
  `  updatedAt: string | null\n` +
  `  found: boolean\n` +
  `}\n\n` +
  `export const ADMIN_DOCS: AdminDoc[] = ${JSON.stringify(docs, null, 2)}\n\n` +
  `export const ADMIN_DOCS_GENERATED_AT = ${JSON.stringify(new Date().toISOString())}\n`

const outDir = path.resolve(__dirname, "..", "src", "generated")
fs.mkdirSync(outDir, { recursive: true })
const outFile = path.join(outDir, "admin-docs.ts")
fs.writeFileSync(outFile, body, "utf8")

console.log(
  `✓ copy-docs: ${docs.filter((d) => d.found).length}/${docs.length} docs baked into src/generated/admin-docs.ts`
)
for (const d of docs) {
  console.log(`  ${d.found ? "•" : "✗"} ${d.title} — ${d.lines} lines, ${d.bytes} B`)
}
