import type { EpicSeed } from "./qa-helpers";

/**
 * Scenariusze testowe — moduł Kuchnia (kitchen).
 * Sub-uprawnienia: kitchen.recipe.create/edit/delete, kitchen.mealplan.edit,
 * kitchen.pantry.edit, kitchen.ai. Gate modułu: module.kitchen.
 */
export const KITCHEN_EPICS: EpicSeed[] = [
  {
    slug: "epic-kitchen-recipes",
    title: "Przepisy",
    description: "CRUD przepisów, slug, archiwizacja, duplikacja, składniki i kroki.",
    stories: [
      {
        slug: "story-kitchen-recipe-create",
        title: "Tworzenie przepisu",
        scenarios: [
          {
            slug: "scenario-kitchen-recipe-create",
            title: "Utworzenie przepisu z podstawowymi danymi",
            type: "positive",
            priority: "P0",
            pre: ["Użytkownik z `module.kitchen` i `kitchen.recipe.create`"],
            steps: ["Otwórz `/kitchen/recipes/new`", "Podaj tytuł, opis, liczbę porcji, czasy, trudność", "Zapisz"],
            expected: [
              "Przepis powstaje z unikalnym slugiem",
              "Domyślnie servings=2, difficulty=„easy”, isPublic=false, cookCount=0",
              "Należy do bieżącego użytkownika (ownerId) lub zespołu (ownerTeamId)",
            ],
          },
          {
            slug: "scenario-kitchen-recipe-no-permission",
            title: "Brak `kitchen.recipe.create` blokuje tworzenie",
            type: "negative",
            priority: "P1",
            pre: ["Użytkownik z `module.kitchen` ale bez `kitchen.recipe.create`"],
            steps: ["Spróbuj utworzyć przepis"],
            expected: ["Akcja tworzenia niedostępna lub odrzucona"],
          },
          {
            slug: "scenario-kitchen-recipe-slug-unique",
            title: "Zmiana tytułu przelicza slug",
            type: "edge",
            priority: "P2",
            pre: ["Istnieje przepis"],
            steps: ["Zmień tytuł na taki sam jak inny przepis", "Zapisz"],
            expected: ["Slug pozostaje unikalny (np. z sufiksem)", "Brak kolizji slugów"],
          },
        ],
      },
      {
        slug: "story-kitchen-recipe-ingredients-steps",
        title: "Składniki i kroki",
        scenarios: [
          {
            slug: "scenario-kitchen-ingredient-add-group",
            title: "Dodawanie składnika z grupą i kolejnością",
            type: "positive",
            priority: "P1",
            pre: ["Edytujesz przepis"],
            steps: ["Dodaj składnik z groupName, ilością, jednostką", "Oznacz jako opcjonalny (isOptional)"],
            expected: ["Składnik w odpowiedniej grupie", "Auto-order jeśli nie podano"],
          },
          {
            slug: "scenario-kitchen-step-reorder",
            title: "Zmiana kolejności kroków",
            type: "positive",
            priority: "P2",
            pre: ["Przepis ma kilka kroków"],
            steps: ["Zmień kolejność (reorderSteps)"],
            expected: ["Kroki przyjmują nową kolejność wg indeksu tablicy"],
          },
          {
            slug: "scenario-kitchen-step-meta",
            title: "Krok z czasem i temperaturą",
            type: "positive",
            priority: "P2",
            pre: ["Edytujesz krok"],
            steps: ["Ustaw durationMin i temperature"],
            expected: ["Krok pokazuje czas i temperaturę w widoku i trybie gotowania"],
          },
        ],
      },
      {
        slug: "story-kitchen-recipe-lifecycle",
        title: "Archiwizacja i duplikacja",
        scenarios: [
          {
            slug: "scenario-kitchen-recipe-archive",
            title: "Archiwizacja przepisu",
            type: "positive",
            priority: "P1",
            pre: ["Posiadasz przepis"],
            steps: ["Zarchiwizuj (archiveRecipe)"],
            expected: ["isArchived=true", "Przepis znika z domyślnej listy (getRecipes filtruje)"],
          },
          {
            slug: "scenario-kitchen-recipe-duplicate",
            title: "Duplikacja przepisu",
            type: "positive",
            priority: "P2",
            pre: ["Istnieje przepis"],
            steps: ["Zduplikuj (duplicateRecipe)"],
            expected: ["Kopia z nowym slugiem i sufiksem „(kopia)”", "Kopia należy do bieżącego użytkownika"],
          },
        ],
      },
    ],
  },
  {
    slug: "epic-kitchen-cook-mode",
    title: "Tryb gotowania",
    description: "Pełnoekranowy widok gotowania ze skalowaniem porcji.",
    stories: [
      {
        slug: "story-kitchen-cook",
        title: "Gotowanie krok po kroku",
        scenarios: [
          {
            slug: "scenario-kitchen-cook-scale",
            title: "Skalowanie porcji w trybie gotowania",
            type: "positive",
            priority: "P1",
            pre: ["Otwierasz `/kitchen/recipes/[id]/cook`"],
            steps: ["Zmień docelową liczbę porcji", "Przejrzyj składniki"],
            expected: ["Ilości skalują się proporcjonalnie (target/recipe.servings)"],
          },
          {
            slug: "scenario-kitchen-cook-complete",
            title: "Zakończenie gotowania oznacza przepis jako ugotowany",
            type: "positive",
            priority: "P1",
            pre: ["Jesteś w trybie gotowania"],
            steps: ["Przejdź przez kroki", "Zakończ gotowanie (markRecipeCooked)"],
            expected: ["cookCount inkrementowany", "lastCookedAt zaktualizowane", "Wpis w aktywności"],
          },
        ],
      },
    ],
  },
  {
    slug: "epic-kitchen-mealplan",
    title: "Plan posiłków",
    description: "Sloty breakfast/lunch/dinner/snack, statusy, drag-drop, plan AI.",
    stories: [
      {
        slug: "story-kitchen-plan-entry",
        title: "Wpisy planu",
        scenarios: [
          {
            slug: "scenario-kitchen-plan-set",
            title: "Dodanie posiłku do slotu w danym dniu",
            type: "positive",
            priority: "P0",
            pre: ["Użytkownik z `kitchen.mealplan.edit`", "Jesteś na `/kitchen/plan`"],
            steps: ["Wybierz dzień i slot (np. obiad)", "Przypisz przepis lub customTitle", "Zapisz (setMealPlanEntry)"],
            expected: ["Wpis pojawia się w slocie", "Status domyślnie PLANNED", "Domyślne servings=2"],
          },
          {
            slug: "scenario-kitchen-plan-empty-blocked",
            title: "Wpis bez przepisu i bez tytułu odrzucony",
            type: "negative",
            priority: "P1",
            pre: ["Tworzysz wpis planu"],
            steps: ["Zostaw recipeId i customTitle puste", "Zapisz"],
            expected: ["Wpis nie powstaje — wymagany przepis LUB własny tytuł"],
          },
          {
            slug: "scenario-kitchen-plan-drag",
            title: "Przeciąganie posiłku między dniami/slotami",
            type: "positive",
            priority: "P2",
            pre: ["Plan zawiera wpis"],
            steps: ["Przeciągnij wpis na inny dzień/slot (moveMealPlanEntry)"],
            expected: ["Wpis przenosi się do nowej daty/slotu"],
          },
        ],
      },
      {
        slug: "story-kitchen-plan-status",
        title: "Statusy posiłków",
        scenarios: [
          {
            slug: "scenario-kitchen-plan-cooked",
            title: "Oznaczenie posiłku jako ugotowany",
            type: "positive",
            priority: "P1",
            pre: ["Wpis planu z przepisem"],
            steps: ["Oznacz jako ugotowany (markMealCooked)"],
            expected: ["status=COOKED, cookedAt ustawione", "Jeśli ma recipeId — Recipe.cookCount++ i lastCookedAt"],
          },
          {
            slug: "scenario-kitchen-plan-skipped",
            title: "Oznaczenie posiłku jako pominięty",
            type: "positive",
            priority: "P2",
            pre: ["Wpis planu"],
            steps: ["Oznacz jako pominięty (markMealSkipped)"],
            expected: ["status=SKIPPED"],
          },
        ],
      },
      {
        slug: "story-kitchen-plan-ai-shopping",
        title: "Plan AI i lista zakupów z planu",
        scenarios: [
          {
            slug: "scenario-kitchen-plan-ai-bulk",
            title: "Wygenerowanie planu tygodnia (AI)",
            type: "positive",
            priority: "P2",
            pre: ["Użytkownik z `kitchen.ai` i `kitchen.mealplan.edit`"],
            steps: ["Uruchom generowanie planu tygodnia (bulkSetMealPlan)"],
            expected: ["Wpisy tworzone atomowo", "replace=true nadpisuje istniejące (date, slot)", "Zwraca added/skipped"],
            notes: "bulkSetMealPlan owinięte w $transaction — bez race condition na duplikaty.",
          },
          {
            slug: "scenario-kitchen-plan-shopping-preview",
            title: "Podgląd listy zakupów z planu",
            type: "positive",
            priority: "P1",
            pre: ["Plan zawiera posiłki z przepisami"],
            steps: ["Uruchom podgląd (previewShoppingListFromPlan)"],
            expected: ["Zwraca zagregowane pozycje (consolidate scala po productId+unit)", "skipPantry odfiltrowuje to, co masz w spiżarni", "Nic nie zapisane (dry-run)"],
          },
          {
            slug: "scenario-kitchen-plan-shopping-generate",
            title: "Wygenerowanie listy zakupów z planu",
            type: "positive",
            priority: "P1",
            pre: ["Podgląd listy zakupów wygląda poprawnie"],
            steps: ["Wygeneruj listę (generateShoppingListFromPlan)"],
            expected: ["Tworzone rekordy Item na liście", "Zwraca addedItems, skippedFromPantry, mergedCount", "Wpis w aktywności"],
          },
        ],
      },
    ],
  },
  {
    slug: "epic-kitchen-pantry",
    title: "Spiżarnia",
    description: "Stany, lokalizacje, daty ważności, stocktake, auto-uzupełnianie.",
    stories: [
      {
        slug: "story-kitchen-pantry-crud",
        title: "Pozycje spiżarni",
        scenarios: [
          {
            slug: "scenario-kitchen-pantry-add",
            title: "Dodanie pozycji do spiżarni",
            type: "positive",
            priority: "P1",
            pre: ["Użytkownik z `kitchen.pantry.edit`"],
            steps: ["Dodaj pozycję z nazwą, ilością, jednostką, lokalizacją, datą ważności"],
            expected: ["Pozycja widoczna, pogrupowana po lokalizacji", "Można ustawić minQuantity i autoShop"],
          },
          {
            slug: "scenario-kitchen-pantry-expiring",
            title: "Alert o produktach kończących termin",
            type: "positive",
            priority: "P1",
            pre: ["Pozycja z expiresAt w ciągu najbliższych dni"],
            steps: ["Otwórz `/kitchen/pantry` lub `/kitchen`"],
            expected: ["Sekcja „kończy się termin” pokazuje pozycje wg getExpiringSoon (rosnąco po dacie)"],
          },
          {
            slug: "scenario-kitchen-pantry-consume",
            title: "Zużycie nie schodzi poniżej zera",
            type: "edge",
            priority: "P2",
            pre: ["Pozycja z ilością 2"],
            steps: ["Zużyj 5 sztuk (consumePantryItem)"],
            expected: ["Ilość = 0 (min 0), nie ujemna"],
          },
        ],
      },
      {
        slug: "story-kitchen-pantry-advanced",
        title: "Stocktake i auto-uzupełnianie",
        scenarios: [
          {
            slug: "scenario-kitchen-stocktake",
            title: "Tryb inwentaryzacji (stocktake)",
            type: "positive",
            priority: "P2",
            pre: ["Jesteś na `/kitchen/pantry/stocktake`"],
            steps: ["Ustaw szybko ilości wielu pozycji", "Zatwierdź"],
            expected: ["Wszystkie ilości zapisane atomowo (bulkSetPantryQuantities w transakcji)"],
          },
          {
            slug: "scenario-kitchen-auto-replenish",
            title: "Auto-uzupełnianie do listy zakupów",
            type: "positive",
            priority: "P2",
            pre: ["Pozycje z autoShop=true i quantity < minQuantity"],
            steps: ["Uruchom auto-uzupełnianie (autoReplenishToList)"],
            expected: ["Brakujące ilości dodane do wskazanej listy zakupów", "Wpis w aktywności"],
          },
          {
            slug: "scenario-kitchen-move-to-pantry",
            title: "Przeniesienie kupionej pozycji do spiżarni",
            type: "positive",
            priority: "P2",
            pre: ["Lista zakupów ma kupioną pozycję"],
            steps: ["Przenieś pozycję do spiżarni (moveItemToPantry)"],
            expected: ["Scala z istniejącą pozycją gdy productId/nazwa pasują, inaczej tworzy nową", "Ownership wg ownerTeamId listy"],
          },
        ],
      },
    ],
  },
  {
    slug: "epic-kitchen-cookbooks-shopping",
    title: "Książki kucharskie i zakupy z przepisu",
    stories: [
      {
        slug: "story-kitchen-cookbooks",
        title: "Książki kucharskie",
        scenarios: [
          {
            slug: "scenario-kitchen-cookbook-create",
            title: "Utworzenie książki kucharskiej",
            type: "positive",
            priority: "P2",
            pre: ["Jesteś na `/kitchen/cookbooks`"],
            steps: ["Utwórz książkę z nazwą, emoji, kolorem"],
            expected: ["Książka widoczna z licznikiem przepisów", "Domyślne emoji `📚`"],
          },
          {
            slug: "scenario-kitchen-cookbook-delete-nullifies",
            title: "Usunięcie książki nie kasuje przepisów",
            type: "positive",
            priority: "P2",
            pre: ["Książka zawiera przepisy"],
            steps: ["Usuń książkę (deleteCookbook)"],
            expected: ["Książka znika", "Przepisy zachowane z cookbookId=null"],
          },
        ],
      },
      {
        slug: "story-kitchen-shop-for-recipe",
        title: "Zakupy z przepisu",
        scenarios: [
          {
            slug: "scenario-kitchen-shop-recipe",
            title: "Dodanie składników przepisu do listy zakupów",
            type: "positive",
            priority: "P1",
            pre: ["Otwarty przepis", "Istnieje lista zakupów"],
            steps: ["Kliknij „Kup na przepis” (shopForRecipe)", "Ustaw liczbę porcji"],
            expected: [
              "Składniki skalowane wg porcji dodane do listy",
              "skipPantry pomija to, co w spiżarni; skipOptional pomija opcjonalne",
              "Tworzony link ItemRecipeOrigin",
            ],
          },
        ],
      },
      {
        slug: "story-kitchen-permission",
        title: "Uprawnienia i mobile",
        scenarios: [
          {
            slug: "scenario-kitchen-no-permission",
            title: "Brak `module.kitchen` — kłódka i blokada",
            type: "negative",
            priority: "P0",
            pre: ["Użytkownik bez `module.kitchen`"],
            steps: ["Sprawdź sidebar", "Wejdź ręcznie na `/kitchen`"],
            expected: ["Pozycja „Kuchnia” wyszarzona z kłódką", "Bezpośredni URL przekierowuje na stronę główną"],
          },
          {
            slug: "scenario-kitchen-ai-gated",
            title: "Funkcje AI tylko z `kitchen.ai`",
            type: "negative",
            priority: "P1",
            pre: ["Użytkownik z `module.kitchen` bez `kitchen.ai`"],
            steps: ["Otwórz listę przepisów, nowy przepis, plan"],
            expected: ["Elementy AI ukryte (flaga hasAI=false przekazana do komponentów)"],
          },
        ],
      },
    ],
  },
];
